import { Activity } from './types';

export const KENKYU_WELFARE_DATA: Activity[] = [
  {
    id: 104,
    facultyName: "",
    department: "研究推進課",
    title: "子どもグループ公開研究会",
    role: "講師, パネリスト",
    type: "講演会",
    organizer: "福祉社会開発研究センター",
    eventName: "災害と子ども〜心のケアからの提言ほか",
    date: "12/13, 1/16",
    location: "赤羽台キャンパス・オンライン",
    target: "一般, 教育関係者, 社会福祉士",
    summary: "児童精神科医や専門家を招き、東日本大震災後の長期的な心のケアの知見共有や、心理的応急処置(PFA)の活用について研鑽。",
    url: "https://sites.google.com/toyo.jp/cdws/news_cr/災害と子ども",
    sdgs: "3"
  },
  {
    id: 105,
    facultyName: "",
    department: "研究推進課",
    title: "オンラインボッチャ協会との協働研究",
    role: "助言・指導, 実演, 調査担当",
    type: "その他",
    organizer: "福祉社会開発研究センター",
    eventName: "年齢・能力を超えた交流イベント",
    date: "通年",
    location: "学内ほか",
    target: "大学生, 一般, 障がいのある方",
    summary: "機器開発への協力や、オンラインボッチャを通じた大学生と障がいのある方の交流イベントを実施し、情報アクセシビリティを推進。",
    url: "https://sites.google.com/toyo.jp/cdws/term5/研究目的概要",
    sdgs: "3"
  },
  {
    id: 106,
    facultyName: "",
    department: "研究推進課",
    title: "世田谷区との協働研究（森田プロジェクト）",
    role: "調査担当, 企画",
    type: "その他",
    organizer: "福祉社会開発研究センター",
    eventName: "地域で孤立しがちな子どもや家庭の支援システム開発",
    date: "通年",
    location: "世田谷区ほか",
    target: "行政機関, 社会人・一般",
    summary: "生活保護受給家庭や母子支援施設の親子を対象とした、当事者主体の困り感理解ツールの開発と実践活動を展開。",
    url: "https://sites.google.com/toyo.jp/cdws/term5/研究目的概要",
    sdgs: "3"
  },
  {
    id: 107,
    facultyName: "",
    department: "研究推進課",
    title: "スペシャルオリンピックス日本との協働研究",
    role: "情報提供, 運営支援",
    type: "その他",
    organizer: "福祉社会開発研究センター",
    eventName: "知的障がい者のソーシャルインクルージョン促進",
    date: "通年",
    location: "全国",
    target: "社会人・一般, 行政機関",
    summary: "アンバサダー活動へのiPad貸与等のICT支援を通じ、知的障がいのある方の意思表明やスポーツを通じた社会参加をバックアップ。",
    url: "https://sites.google.com/toyo.jp/cdws/term5/研究目的概要",
    sdgs: "3"
  },
  {
    id: 108,
    facultyName: "",
    department: "研究推進課",
    title: "分身ロボット OriHime を介した教育支援",
    role: "助言・指導, 調査担当",
    type: "その他",
    organizer: "福祉社会開発研究センター・世田谷区",
    eventName: "医療的ケア児への遠隔授業参加支援",
    date: "通年",
    location: "世田谷区",
    target: "教育関係者, 行政機関",
    summary: "重症化リスクの高い医療的ケア児が、分身ロボットを用いて自宅から教室の授業に参加できるよう共同研究と実装支援を実施。",
    url: "https://sites.google.com/toyo.jp/cdws/term5/研究目的概要",
    sdgs: "3"
  }
];
