import { Activity } from './types';

export const TOSHO_DATA: Activity[] = [
  // --- 白山図書館 ---
  {
    id: 145,
    facultyName: "",
    department: "図書事務課（白山）",
    title: "近隣区民への白山図書館開放",
    role: "その他",
    type: "その他",
    organizer: "白山図書館",
    eventName: "近隣区民への白山図書館開放",
    date: "4/1-3/31",
    location: "白山図書館",
    target: "社会人・一般",
    summary: "利用対象：文京区・板橋区・北区内在住の満18歳以上の社会人の方（学生・受験生を除く）。利用期間：学生夏季休暇および春季休暇中。利用サービス：図書館資料（冊子体）の館内閲覧、OPACでの所蔵検索、閲覧席の利用、著作権範囲内における複写サービスを提供。",
    url: "https://sites.google.com/toyo.jp/library/use/others",
    sdgs: "4"
  },
  {
    id: 146,
    facultyName: "",
    department: "図書事務課（白山）",
    title: "附属高校生への白山図書館及び赤羽台図書館開放",
    role: "その他",
    type: "その他",
    organizer: "白山図書館・赤羽台図書館",
    eventName: "附属高等学校生への開放",
    date: "8/1-3/31",
    location: "白山図書館・赤羽台図書館",
    target: "高校生",
    summary: "利用対象：附属高校生。利用期間：通年（ただし、7月・1月は利用不可）。館内閲覧、所蔵検索、閲覧席利用のほか、図書館資料（冊子体）の館外貸出も可能としています。",
    url: "https://sites.google.com/toyo.jp/library/use/others",
    sdgs: "4"
  },
  {
    id: 147,
    facultyName: "",
    department: "図書事務課（白山）",
    title: "近隣中学・高校生への白山図書館開放",
    role: "その他",
    type: "その他",
    organizer: "白山図書館",
    eventName: "近隣中学・高校生への白山図書館開放",
    date: "8/1-3/31",
    location: "白山図書館",
    target: "中学生, 高校生",
    summary: "利用対象：近隣中学・高校生（京華、駒込、広尾学園小石川等）。利用期間：通年（ただし、7月・1月は利用不可）。館内閲覧、OPAC検索、閲覧席利用などのサービスを提供しています。",
    url: "https://sites.google.com/toyo.jp/library/use/others",
    sdgs: "4"
  },
  {
    id: 148,
    facultyName: "",
    department: "図書事務課（白山）",
    title: "『東洋大学附属図書館 貴重書デジタルアーカイブ』の公開",
    role: "その他",
    type: "その他",
    organizer: "白山図書館",
    eventName: "貴重書デジタルアーカイブの公開",
    date: "4/1-3/31",
    location: "オンライン",
    target: "一般, 研究者, 教育関係者等",
    summary: "本学附属図書館で所蔵する貴重書及びそれに準じる資料をデジタルアーカイブ化し、『東洋大学附属図書館 貴重書デジタルアーカイブ』にて順次公開している。",
    url: "https://www.i-repository.net/il/meta_pub/G0000604kichosho",
    sdgs: "4"
  },
  {
    id: 149,
    facultyName: "",
    department: "図書事務課（白山）",
    title: "国文学研究資料館「国書データベース」での本学所蔵古典籍の画像公開",
    role: "その他",
    type: "その他",
    organizer: "白山図書館",
    eventName: "国書データベース連携",
    date: "2024/3/27-3/31",
    location: "オンライン",
    target: "一般, 研究者, その他",
    summary: "本学附属図書館は、国文学研究資料館のプロジェクト「日本語の歴史的典籍の国際共同研究ネットワーク構築計画」と連携し、2024年3月27日（水）より「国書データベース」にて本学所蔵の古典籍の画像公開を開始した。対象は「哲学堂文庫」「百人一首コレクション」「吉田幸一旧蔵書（古典文庫）」で、今後順次公開予定。",
    url: "https://kokusho.nijl.ac.jp/page/list-toyodaitetsugakudo.html",
    sdgs: "4"
  },
  {
    id: 150,
    facultyName: "",
    department: "図書事務課（白山）",
    title: "貴重書及びそれに準じる資料の掲載・放映",
    role: "その他",
    type: "その他",
    organizer: "白山図書館",
    eventName: "資料の掲載・放映協力",
    date: "4/1-3/31",
    location: "外部機関、テレビ番組等",
    target: "一般, メディア等",
    summary: "本学附属図書館で所蔵する貴重書及びそれに準じる資料の画像データ等を提供。湯本豪一記念日本妖怪博物館企画展での掲載資料『稻亭物怪録』、NHK・Eテレ「3か月でマスターする江戸時代」での『好色一代男』『日本永代蔵』放映など、学術・文化の振興に寄与しました。",
    url: "―",
    sdgs: "4"
  },
  // --- 川越図書館 ---
  {
    id: 151,
    facultyName: "",
    department: "図書事務課（川越）",
    title: "近隣地域市民への川越図書館開放",
    role: "その他",
    type: "その他",
    organizer: "川越図書館",
    eventName: "近隣地域市民への川越図書館開放",
    date: "4/1-3/31",
    location: "川越図書館",
    target: "中学生, 高校生, 社会人・一般等",
    summary: "川越市立図書館・鶴ヶ島市立図書館・坂戸市立図書館の利用証（利用カード）を登録している３市に在住、または在勤・在学している中学生以上を対象に閲覧利用を認めている。",
    url: "https://www.toyo.ac.jp/library/guidance/gakugai/",
    sdgs: "4"
  },
  // --- 朝霞図書館 ---
  {
    id: 152,
    facultyName: "",
    department: "図書事務課（朝霞）",
    title: "近隣地域市民への朝霞図書館開放",
    role: "その他",
    type: "その他",
    organizer: "朝霞図書館",
    eventName: "近隣地域市民への朝霞図書館開放",
    date: "8/3-9/19, 2/1-3/31",
    location: "朝霞図書館",
    target: "中学生, 高校生, 社会人・一般等",
    summary: "朝霞市・志木市・新座市・和光市に在住または在勤・在学している中学生以上の方を対象として閲覧利用を許可している。利用可能期間は、学生夏季休暇および春季休暇中の開館日。館外貸出は不可ですが、館内での複写（著作権範囲内）は可能です。",
    url: "https://sites.google.com/toyo.jp/library/use/others",
    sdgs: "4"
  },
  // --- 赤羽台図書館 ---
  {
    id: 153,
    facultyName: "",
    department: "図書事務課（赤羽台）",
    title: "北区区民への赤羽台図書館開放",
    role: "その他",
    type: "その他",
    organizer: "赤羽台図書館",
    eventName: "北区区民への開放",
    date: "4/1-3/31",
    location: "赤羽台図書館",
    target: "社会人・一般",
    summary: "北区内在住の満18歳以上の社会人で北区立図書館の利用登録者に対して、長期休暇期間に図書館を開放している。2024年度は夏季（8/5-9/19）および春季（2/3-3/31）に実施しました。",
    url: "https://sites.google.com/toyo.jp/akabanedailibrary/",
    sdgs: "4"
  },
  {
    id: 154,
    facultyName: "",
    department: "図書事務課（赤羽台）",
    title: "北区区民への「こども図書館『えーる』」開放",
    role: "その他",
    type: "その他",
    organizer: "赤羽台図書館",
    eventName: "こども図書館『えーる』の開放",
    date: "4/1-3/31",
    location: "赤羽台図書館",
    target: "幼稚園以下, 保護者",
    summary: "北区内在住の未就学児とその保護者で、保護者が北区立図書館の利用登録者に対して、通年で「こども図書館『えーる』」を開放している（試験期等を除く）。親子で大学図書館の絵本や設備に親しむ機会を提供しています。",
    url: "https://sites.google.com/toyo.jp/akabanedailibrary/",
    sdgs: "4"
  },
  {
    id: 155,
    facultyName: "",
    department: "図書事務課（赤羽台）",
    title: "菊地章太館長 特別講演会 「パリへ行こう！～オリンピックの舞台へ～」",
    role: "講師, 企画, 運営参加・支援, その他",
    type: "講演会",
    organizer: "赤羽台図書館",
    eventName: "館長特別講演会",
    date: "6/24",
    location: "赤羽台図書館",
    target: "幼稚園以下, 小学生, 一般等",
    summary: "パリオリンピックで歴史ある街並みを活かした競技会場が話題になったことにちなみ、フランスの街々を映像と音楽で楽しむ企画。5月末に現地を訪れた菊地館長による最新情報も盛り込まれました。",
    url: "https://x.com/TOYOLibrary_asa/status/1800332885104435707",
    sdgs: "4"
  },
  {
    id: 156,
    facultyName: "",
    department: "図書事務課（赤羽台）",
    title: "おとなの読書会《あかばねだい絵本ラウンジ》",
    role: "企画, 運営参加・支援, その他",
    type: "その他",
    organizer: "赤羽台図書館",
    eventName: "あかばねだい絵本ラウンジ",
    date: "7/22, 2/27",
    location: "赤羽台図書館",
    target: "大学生, 一般等",
    summary: "絵本への大人の関心の高まりが注目されていることから、対象を北区民、加盟大学学生、本学関係者等とする絵本の読書会を開催。参加者は思い思いに絵本の読み聞かせを行い、作品への思い入れや知識を語り合いました。",
    url: "https://x.com/TOYOLibrary_asa/status/1806127823910031516",
    sdgs: "4"
  },
  {
    id: 157,
    facultyName: "",
    department: "図書事務課（赤羽台）",
    title: "映画上映会 ＆ 監督トークイベント「1/10 Fukushimaをきいてみる 2023」",
    role: "企画, 運営参加・支援, その他",
    type: "その他",
    organizer: "赤羽台図書館",
    eventName: "映画上映会 ＆ 監督トークイベント",
    date: "11/12",
    location: "赤羽台図書館",
    target: "大学生, 一般等",
    summary: "福島の被災地に住む人、関わる人に話を聞くドキュメンタリー映画の上映会。上映後、監督の古波津陽氏とオンラインでつなぎ、会場の学生と双方向でのトークや質疑応答を行った。関連資料の展示も同時実施。",
    url: "https://x.com/TOYOLibrary_asa/status/1842111789691240775",
    sdgs: "11"
  },
  {
    id: 158,
    facultyName: "",
    department: "図書事務課（赤羽台）",
    title: "演奏＆講演会「西洋楽器の夕べⅡ」",
    role: "企画, 運営参加・支援, その他",
    type: "その他",
    organizer: "赤羽台図書館",
    eventName: "西洋楽器の夕べⅡ",
    date: "12/17",
    location: "赤羽台図書館",
    target: "幼稚園以下, 小学生, 一般等",
    summary: "赤羽台図書館長、菊地章太教授による西洋楽器の演奏会を実施。映像資料を流しながら楽器の歴史的背景や文化についての解説も行いました。昨年大好評だった企画の第2弾です。",
    url: "https://x.com/TOYOLibrary_asa/status/1871066921086726407",
    sdgs: "4"
  },
  {
    id: 159,
    facultyName: "",
    department: "図書事務課（赤羽台）",
    title: "東洋大学「読書サポート犬」プログラム わんわん読書タイム",
    role: "助言・指導, 企画, 運営参加・支援, その他",
    type: "その他",
    organizer: "赤羽台図書館 ＆ 人間科学総合研究所",
    eventName: "わんわん読書タイム",
    date: "1/11",
    location: "赤羽台図書館",
    target: "小学生, 保護者, 市民団体",
    summary: "学齢期の子どもにたちに寄り添い、安心して楽しい読書を体験してもらうための取り組み。JAHAのセラピードッグ基準を満たした犬と、本学学生ボランティアによる運営。子どもが犬に対して1対1で読み聞かせを行う。大学での本格実施は本学が初となります。北区の子ども食堂などの協力も得て開催しました。",
    url: "https://x.com/TOYOLibrary_asa/status/1876466425415754092",
    sdgs: "4"
  }
];