import { Activity } from './types';

export const EDUCATION_DATA: Activity[] = [
  {
    id: 10,
    facultyName: "大江 啓賢",
    department: "文学部 教育学科",
    title: "学校研究（指導助言）",
    role: "講師, 助言・指導",
    type: "その他",
    organizer: "埼玉県立川島ひばりが丘特別支援学校",
    eventName: "特別支援学校 学校研究",
    date: "2022/4/1～2025/3/31",
    location: "埼玉県立川島ひばりが丘特別支援学校",
    target: "教育関係者",
    summary: "実施主体が学校研究として行う研究授業について「授業の指導助言」および各教育課程のテーマに沿った「指導講評」を年間3回実施。",
    url: "",
    sdgs: "4"
  },
  {
    id: 11,
    facultyName: "大江 啓賢",
    department: "文学部 教育学科",
    title: "教育職員免許法認定講習",
    role: "講師",
    type: "資格認定講習",
    organizer: "埼玉県教育委員会",
    eventName: "教育職員免許法認定講習",
    date: "8/5-8/6, 12/26-12/27",
    location: "埼玉県県民活動総合センター, 埼玉県総合教育センター",
    target: "教育関係者",
    summary: "埼玉県教育委員会主催の「教育職員免許法認定講習」にて、現職教員を対象とした講師を担当。",
    url: "",
    sdgs: "4"
  },
  {
    id: 12,
    facultyName: "大江 啓賢",
    department: "文学部 教育学科",
    title: "教育職員免許法認定講習（さいたま市）",
    role: "講師",
    type: "資格認定講習",
    organizer: "さいたま市教育委員会",
    eventName: "教育職員免許法認定講習",
    date: "8/7-8/8",
    location: "さいたま市立さくら草特別支援学校",
    target: "教育関係者",
    summary: "さいたま市教育委員会主催の「教育職員免許法認定講習」にて講師を担当。",
    url: "",
    sdgs: "4"
  },
  {
    id: 13,
    facultyName: "大江 啓賢",
    department: "文学部 教育学科",
    title: "幼稚園研修会講師",
    role: "講師",
    type: "その他",
    organizer: "学校法人細渕学園 まつもと幼稚園",
    eventName: "園内研修会「幼稚園における発達障害幼児の理解と対応」",
    date: "7/10",
    location: "まつもと幼稚園",
    target: "教育関係者",
    summary: "幼稚園における発達障害幼児（ASD、ADHD等）の理解と対応をテーマに、現場教員への指導・講演を実施。",
    url: "",
    sdgs: "4"
  },
  {
    id: 14,
    facultyName: "大江 啓賢",
    department: "文学部 教育学科",
    title: "専門研修会講師",
    role: "講師",
    type: "その他",
    organizer: "日本特別支援教育オンライン学会",
    eventName: "会員向け専門研修会「肢体不自由児・病弱児の理解と支援」",
    date: "3/20",
    location: "オンライン",
    target: "学会会員, 教育・保育・福祉関係者",
    summary: "オンラインによる専門研修会にて講師を担当し、専門的な知見の普及に努めた。",
    url: "",
    sdgs: "4"
  }
];