import { Activity } from './types';

export const KENKYU_PPP_DATA: Activity[] = [
  {
    id: 84,
    facultyName: "",
    department: "研究推進課",
    title: "省インフラ研究会",
    role: "助言・指導, 情報提供, 企画",
    type: "研究指導",
    organizer: "PPP 研究センター",
    eventName: "持続可能なインフラのあり方検討",
    date: "通年",
    location: "東洋大学",
    target: "企業",
    summary: "老朽化や人口減少に正面から向き合い、物理的なインフラに過度に依存せず質の高い生活を維持できる社会のあり方を産学連携で検討。",
    url: "https://www.pppschool.jp/pppc/infra/index.html",
    sdgs: "9"
  },
  {
    id: 85,
    facultyName: "",
    department: "研究推進課",
    title: "特別セミナー「PPP/PFI推進のための新しい戦略」",
    role: "講師, パネリスト",
    type: "講演会",
    organizer: "東洋大学・国土交通省 共催",
    eventName: "名古屋会場・大阪会場セミナー",
    date: "8/19, 8/20",
    location: "名古屋、大阪",
    target: "研究者, 企業, 行政機関",
    summary: "国のPPP/PFI推進アクションプランを受け、分野横断型や地方創生に資する民間資金活用事業の最新動向を共有。",
    url: "https://www.pppschool.jp/news/20240711-06243.html",
    sdgs: "8, 9, 17"
  },
  {
    id: 86,
    facultyName: "",
    department: "研究推進課",
    title: "2024年度 リカレント講座",
    role: "講師, 運営",
    type: "セミナー・ワークショップ",
    organizer: "PPP 研究センター",
    eventName: "まちづくりとPPP ～まちづくりの価値観の転換～",
    date: "9/17",
    location: "白山キャンパススカイホール",
    target: "大学院生, 修了生, 企業",
    summary: "修了生や実務家を対象に、人口減少時代の都市再生法に基づくPPP手法のアップデートと情報交換会を実施。",
    url: "https://www.pppschool.jp/news/20240917-06573.html",
    sdgs: "4, 8, 11, 17"
  },
  {
    id: 87,
    facultyName: "",
    department: "研究推進課",
    title: "第19回 国際PPPフォーラム",
    role: "司会, 講師",
    type: "講演会",
    organizer: "東洋大学（内閣府・総務省・国交省 後援）",
    eventName: "PPPの小型化：地方圏での持続的発展に向けて",
    date: "10/21",
    location: "白山キャンパススカイホール",
    target: "行政機関, 企業, 一般",
    summary: "スモールコンセッション等、小規模な自治体でも導入可能なPPP手法について、国内外の事例を交えてガバナンスとコスト吸収策を議論。",
    url: "https://www.pppschool.jp/news/20240924-06690.html",
    sdgs: "4, 8, 11, 17"
  },
  {
    id: 88,
    facultyName: "",
    department: "研究推進課",
    title: "【PPP】公開講義（連続トーク）",
    role: "司会, 講師, 助言・指導",
    type: "セミナー・ワークショップ",
    organizer: "PPP 研究センター",
    eventName: "地域リーダー論・公共施設マネジメント・Global PPP Financeほか",
    date: "10/29-1/11",
    location: "白山キャンパス・オンライン",
    target: "大学生, 一般, 行政機関",
    summary: "世界銀行駐日代表や地方首長、建築家などをゲストに招き、デジタル地域社会やインフラ輸出など多岐にわたるPPP実務を公開。",
    url: "https://www.pppschool.jp/news/20241008-06815.html",
    sdgs: "4, 8, 11, 17"
  }
];
