import { Activity } from './types';

export const KENKYU_ASIA_PPP_DATA: Activity[] = [
  {
    id: 72,
    facultyName: "",
    department: "研究推進課",
    title: "APPPI Open Seminar on Kyrgyz Republic",
    role: "司会, 情報提供",
    type: "セミナー・ワークショップ",
    organizer: "アジアPPP 研究所",
    eventName: "PPP Environment in Kyrgyz Republic",
    date: "5/20",
    location: "東洋大学",
    target: "研究者, 行政機関, 企業",
    summary: "キルギス共和国のPPPセンター代表団を招き、同国の法制度や今後のインフラプロジェクトに関する最新情報を共有。",
    url: "https://www.apppi.net/news/20240521-06701.html",
    sdgs: "4, 9, 11, 17"
  },
  {
    id: 73,
    facultyName: "",
    department: "研究推進課",
    title: "ADB Joint Seminar on Gender Equality",
    role: "司会, 情報提供",
    type: "セミナー・ワークショップ",
    organizer: "アジアPPP研究所・アジア開発銀行（ADB）共催",
    eventName: "Role of the PPPs in Promoting Gender Equality",
    date: "7/6",
    location: "東洋大学",
    target: "研究者, 企業",
    summary: "インフラ整備プロジェクト（PPP）におけるジェンダー平等の促進について、ADBの専門家を招き実践的な手法を議論。",
    url: "https://www.apppi.net/news/20240708-06513.html",
    sdgs: "4, 5, 17"
  },
  {
    id: 74,
    facultyName: "",
    department: "研究推進課",
    title: "Taiwan-Japan PPP Exchange",
    role: "パネリスト, 運営",
    type: "その他",
    organizer: "アジアPPP 研究所",
    eventName: "APPPI Hosted Taiwan Based Asia Pacific PPP Association",
    date: "8/28",
    location: "白山キャンパス",
    target: "学術団体, 研究者",
    summary: "台湾のPPP協会委員会を迎え、日台間のPPP慣習の違いや成功事例について相互プレゼンテーションと意見交換を実施。",
    url: "https://www.apppi.net/news/20240906-06502.html",
    sdgs: "4, 9, 11, 17"
  },
  {
    id: 75,
    facultyName: "",
    department: "研究推進課",
    title: "BID Seminar: Times Square Case Study",
    role: "司会, 企画",
    type: "講演会",
    organizer: "アジアPPP 研究所",
    eventName: "Business Improvement Districts: The Case of Times Square",
    date: "10/17",
    location: "オンライン",
    target: "大学生, 行政機関, 企業",
    summary: "ニューヨークのタイムズスクエアを例に、民間主導の都市マネジメント手法（BID）の効果と課題をNYU教授が解説。",
    url: "https://www.apppi.net/news/20241004-06805.html",
    sdgs: "4, 9, 11, 17"
  },
  {
    id: 76,
    facultyName: "",
    department: "研究推進課",
    title: "Egypt PPP Environment Seminar",
    role: "コメンテーター, 情報提供",
    type: "講演会",
    organizer: "アジアPPP 研究所",
    eventName: "PPP Environment in Egypt",
    date: "12/16",
    location: "東洋大学",
    target: "社会人・一般, 行政機関",
    summary: "在エジプト日本大使館コンサルタントを招き、同国の主要インフラセクターや現在進行中のPPPプロジェクトの状況を報告。",
    url: "https://www.apppi.net/news/20241218-07323.html",
    sdgs: "4, 9, 11, 17"
  },
  {
    id: 77,
    facultyName: "",
    department: "研究推進課",
    title: "ウォーターPPPの概観と各地の取り組み",
    role: "司会, 企画",
    type: "講演会",
    organizer: "アジアPPP 研究所",
    eventName: "APPPI Open seminar",
    date: "2/25",
    location: "東洋大学",
    target: "企業, 行政機関, 大学院生",
    summary: "下水道システムの課題解決に向けた日本政府の「ウォーターPPP」推進施策について、最新のコンセッション事例等を交えて解説。",
    url: "―",
    sdgs: "6, 9, 17"
  }
];
