import { Activity } from './types';

export const KENKYU_ASIA_CULT_DATA: Activity[] = [
  {
    id: 52,
    facultyName: "",
    department: "研究推進課",
    title: "国際シンポジウム「Muslim Philanthropy in Japan」",
    role: "司会, 企画",
    type: "セミナー・ワークショップ",
    organizer: "アジア文化研究所（子島プロジェクト）",
    eventName: "Muslim Philanthropy in Japan",
    date: "6/2",
    location: "白山キャンパススカイホール",
    target: "研究者, 社会人・一般",
    summary: "在日ムスリムによる災害支援やパンデミック下の活動を通じ、日本におけるイスラーム的な社会貢献（フィランソロピー）の現状と多文化共生の可能性を議論。",
    url: "https://sites.google.com/toyo.jp/acri/news_cr/20240602",
    sdgs: "3, 10"
  },
  {
    id: 53,
    facultyName: "",
    department: "研究推進課",
    title: "グローバル地中海映画上映会",
    role: "コメンテーター, 企画",
    type: "セミナー・ワークショップ",
    organizer: "アジア文化研究所（グローバル地中海地域研究拠点）",
    eventName: "第2回〜第5回上映会（『はじめてのおもてなし』ほか）",
    date: "6/24-12/12",
    location: "白山キャンパス各教室",
    target: "大学生, 研究者, 一般",
    summary: "トルコ、スロヴェニア、ドイツ等の映画上映と専門家による解説を通じ、移民・難民問題や異文化接触などの現代社会の諸問題を多角的に理解する。",
    url: "https://sites.google.com/toyo.jp/globalmediterranean/activities/240624filmscreening",
    sdgs: "4, 5, 10, 11, 16, 17"
  },
  {
    id: 54,
    facultyName: "",
    department: "研究推進課",
    title: "第1回 アジア文化研究所 研究例会「米中対立下の中国企業動向」",
    role: "パネリスト, 企画",
    type: "講演会",
    organizer: "アジア文化研究所（郝班・後藤プロジェクト）",
    eventName: "「一帯一路」構想及びAIIBとの関連を中心に",
    date: "7/29",
    location: "白山キャンパススカイホール",
    target: "研究者, 学生",
    summary: "中国企業のイノベーション活動や対外投資動向について、現地調査に基づいた専門的な報告と議論を実施。",
    url: "https://sites.google.com/toyo.jp/acri/news_cr/20240729",
    sdgs: "4, 8, 9"
  },
  {
    id: 55,
    facultyName: "",
    department: "研究推進課",
    title: "第4回 在日イスラーム校ワークショップ",
    role: "企画, 運営",
    type: "セミナー・ワークショップ",
    organizer: "アジア文化研究所（井上助成・子島プロジェクト）",
    eventName: "Broadening Our Horizons",
    date: "9/15",
    location: "白山キャンパス A102",
    target: "教育関係者, 研究者",
    summary: "日本国内の複数のイスラーム校関係者を招き、学校運営の現状や課題、第2世代のアイデンティティ形成について情報共有を実施。",
    url: "https://sites.google.com/toyo.jp/acri/news_cr/20240915",
    sdgs: "4, 10"
  },
  {
    id: 56,
    facultyName: "",
    department: "研究推進課",
    title: "公開シンポジウム「日中異文化接触と教育の課題」",
    role: "司会, 企画",
    type: "セミナー・ワークショップ",
    organizer: "アジア文化研究所",
    eventName: "多文化アジアにおける異文化接触",
    date: "10/12",
    location: "白山キャンパス・オンライン",
    target: "研究者, 社会人・一般",
    summary: "創立者・井上円了の台湾体験や、華中科技大学との20年以上にわたる交流の歴史を振り返りつつ、日中間の教育的課題と展望を考察。",
    url: "https://sites.google.com/toyo.jp/acri/news_cr/20241012",
    sdgs: "4, 10"
  },
  {
    id: 57,
    facultyName: "",
    department: "研究推進課",
    title: "特別WS「表出するマージナリティ」",
    role: "コメンテーター, 企画",
    type: "セミナー・ワークショップ",
    organizer: "アジア文化研究所（グローバル地中海拠点）",
    eventName: "映像に見るヨーロッパと中央アジアの非日常のパフォーマンス",
    date: "11/9",
    location: "白山キャンパス125記念ホール",
    target: "研究者, 一般",
    summary: "映像人類学の手法を用い、フランスのジプシー祝祭やウズベキスタンの霊媒儀礼を通じ、社会の周縁に置かれた存在の現出を考察。",
    url: "https://sites.google.com/toyo.jp/globalmediterranean/activities/241109theexpressivemarginality",
    sdgs: "4, 10"
  },
  {
    id: 58,
    facultyName: "",
    department: "研究推進課",
    title: "国際シンポジウム「日中における経済発展と金融政策」",
    role: "講師, 企画",
    type: "講演会",
    organizer: "アジア文化研究所・復旦大学発展研究院 共催",
    eventName: "国際シンポジウム",
    date: "11/15",
    location: "白山キャンパス井上円了ホール",
    target: "研究者, 一般, 企業",
    summary: "中国の「一帯一路」政策やAIIB、日中間の金融・経済政策に関する共同研究の成果を広く公開し、企業活動にも有益な視点を提供。",
    url: "https://sites.google.com/toyo.jp/acri/news_cr/20241115",
    sdgs: "4, 8, 9"
  },
  {
    id: 59,
    facultyName: "",
    department: "研究推進課",
    title: "国際シンポジウム「日露戦争”辛勝”の残響」",
    role: "講師, 企画",
    type: "講演会",
    organizer: "アジア文化研究所（特別研究費）・グローバル地中海 共催",
    eventName: "The Echoes of the Narrow Victory over the Russo-Japanese War",
    date: "12/7",
    location: "白山キャンパススカイホール",
    target: "研究者, 学術団体",
    summary: "開戦120周年を記念し、日本の勝利がイスラーム圏やグローバルヒストリー、各地の独立運動に与えた影響を再考。",
    url: "https://sites.google.com/toyo.jp/globalmediterranean/activities/231207echoesofvictory",
    sdgs: "1, 10, 16"
  },
  {
    id: 60,
    facultyName: "",
    department: "研究推進課",
    title: "第16回フォーラム「みえない移民労働者」",
    role: "司会, 企画",
    type: "セミナー・ワークショップ",
    organizer: "アジア文化研究所・白山人類学会 共催",
    eventName: "日本・台湾に生きるインドネシア人と共生の諸相",
    date: "12/21",
    location: "白山キャンパススカイホール・オンライン",
    target: "一般, 研究者",
    summary: "漁業や製造業に従事するインドネシア人移民労働者の生活世界と、地域社会との共生（非共生）の現状を具体的事例から検討。",
    url: "https://www.toyo.ac.jp/news/20241217-16648.html",
    sdgs: "4, 8, 17"
  }
];
