import { Activity } from './types';

export const LITERATURE_DATA: Activity[] = [
  {
    id: 1,
    facultyName: "高松 亮太",
    department: "文学部 日本文学文化学科",
    title: "賀茂真淵記念館 記念館アカデミー",
    role: "講師",
    type: "講演会",
    organizer: "賀茂真淵記念館",
    eventName: "市民講座 記念館アカデミー「真淵の註釈で「百人一首」をよむ」",
    date: "7/5, 9/6, 10/18",
    location: "賀茂真淵記念館",
    target: "社会人・一般",
    summary: "静岡県浜松市の賀茂真淵記念館が行っている市民講座「記念館アカデミー」で、「真淵の註釈で「百人一首」をよむ」と題して全3回の講座を行った。",
    url: "https://www.mabuchi-kinenkan.jp/event/index.html",
    sdgs: "4"
  },
  {
    id: 2,
    facultyName: "高松 亮太",
    department: "文学部 日本文学文化学科",
    title: "第38回東洋大学 現代学生百人一首",
    role: "助言・指導\n運営参加・支援\n報告書執筆\n報告",
    type: "調査, その他",
    organizer: "東洋大学広報課",
    eventName: "第38回東洋大学 現代学生百人一首",
    date: "―",
    location: "東洋大学",
    target: "小学生, 中学生, 高校生, 大学生, 大学院生",
    summary: "第38回東洋大学 現代学生百人一首にて選考委員会委員を務め、選考を行った。",
    url: "https://www.toyo.ac.jp/social/issyu/",
    sdgs: "4"
  },
  {
    id: 3,
    facultyName: "高松 亮太",
    department: "文学部 日本文学文化学科",
    title: "静岡県高等学校国語教育研究会　西部支部研修会",
    role: "講師",
    type: "講演会",
    organizer: "静岡県高等学校国語教育研究会",
    eventName: "西部支部研修会",
    date: "11/7",
    location: "賀茂真淵記念館",
    target: "教育関係者",
    summary: "静岡県高等学校国語教育研究会西部支部研修会で「賀茂真淵の万葉主義」と題して講演を行った。",
    url: "",
    sdgs: "4"
  },
  {
    id: 4,
    facultyName: "川内 佑毅",
    department: "文学部 日本文学文化学科",
    title: "篆刻体験コーナー講師",
    role: "講師",
    type: "セミナー・ワークショップ",
    organizer: "全日本篆刻連盟",
    eventName: "篆刻体験コーナー",
    date: "5/19",
    location: "セントラルミュージアム銀座",
    target: "社会人・一般",
    summary: "文京区書道連盟主催の篆刻講習にて講師を務め、指導を行った。",
    url: "https://researchmap.jp/g0000220027/social_contribution/48442794",
    sdgs: "4"
  },
  {
    id: 5,
    facultyName: "川内 佑毅",
    department: "文学部 日本文学文化学科",
    title: "「わくわくワークショップ」アシスタント担当",
    role: "助言・指導",
    type: "セミナー・ワークショップ",
    organizer: "社団法人日展",
    eventName: "「わくわくワークショップ」",
    date: "11/10",
    location: "国立新美術館 三階講堂",
    target: "2,3,8",
    summary: "社団法人日展主催の「わくわくワークショップ」にてアシスタントを担当し、助言・指導を行った。",
    url: "https://researchmap.jp/g0000220027/social_contribution/48442759",
    sdgs: "4"
  },
  {
    id: 6,
    facultyName: "大田 悦子",
    department: "文学部 英米文学科",
    title: "（青森県）進学力を高める高校支援事業",
    role: "助言・指導\n情報提供",
    type: "研究指導",
    organizer: "青森県立三本木高等学校",
    eventName: "（青森県）進学力を高める高校支援事業",
    date: "―",
    location: "青森県立三本木高等学校",
    target: "教育関係者",
    summary: "生徒の発信力強化のための英語指導力向上を目的に当該校で取り組んでいる英語授業指導改善研究会（年3回）に助言者として参加。7/5（オンライン）、10/24ー25 、2/４－5（＠三本木高校）計3回。",
    url: "",
    sdgs: "4"
  },
  {
    id: 7,
    facultyName: "大田 悦子",
    department: "文学部 英米文学科",
    title: "Sherpa (Senior High English Reform Project ALC)",
    role: "出演, コメンテーター, 司会, 編集, 講師, 助言・指導, 情報提供, 企画, 運営参加・支援, 実演, 調査担当",
    type: "セミナー・ワークショップ",
    organizer: "株式会社アルク",
    eventName: "Sherpa Channel / セミナー",
    date: "2010/3-現在",
    location: "オンライン",
    target: "大学生, 教育関係者, 社会人・一般",
    summary: "高校英語授業改善に貢献することを目的とした活動。教員向けのセミナーやYouTube配信「Sherpa Channel」を通じて指導法の提案等を行っている。",
    url: "https://alc-nds.com/ltaf/2021/09/20/sherpa/",
    sdgs: "4"
  }
];
