import { Activity } from './types';

export const LITERATURE_DATA: Activity[] = [
  {
    id: 1,
    facultyName: "高松 亮太",
    department: "文学部 日本文学文化学科",
    title: "賀茂真淵記念館 記念館アカデミー",
    role: "講師",
    type: "講演会",
    organizer: "賀茂真淵記念館",
    eventName: "市民講座 記念館アカデミー「真淵の註釈で「百人一首」をよむ」",
    date: "7/5, 9/6, 10/18",
    location: "賀茂真淵記念館",
    target: "社会人・一般",
    summary: "静岡県浜松市の賀茂真淵記念館が行っている市民講座「記念館アカデミー」で、「真淵の註釈で「百人一首」をよむ」と題して全3回の講座を行った。",
    url: "https://www.mabuchi-kinenkan.jp/event/index.html",
    sdgs: "4"
  },
  {
    id: 2,
    facultyName: "高松 亮太",
    department: "文学部 日本文学文化学科",
    title: "第38回東洋大学 現代学生百人一首",
    role: "助言・指導\n運営参加・支援\n報告書執筆\n報告",
    type: "調査, その他",
    organizer: "東洋大学広報課",
    eventName: "第38回東洋大学 現代学生百人一首",
    date: "―",
    location: "東洋大学",
    target: "小学生, 中学生, 高校生, 大学生, 大学院生",
    summary: "第38回東洋大学 現代学生百人一首にて選考委員会委員を務め、選考を行った。",
    url: "https://www.toyo.ac.jp/social/issyu/",
    sdgs: "4"
  },
  {
    id: 3,
    facultyName: "高松 亮太",
    department: "文学部 日本文学文化学科",
    title: "静岡県高等学校国語教育研究会　西部支部研修会",
    role: "講師",
    type: "講演会",
    organizer: "静岡県高等学校国語教育研究会",
    eventName: "西部支部研修会",
    date: "11/7",
    location: "賀茂真淵記念館",
    target: "教育関係者",
    summary: "静岡県高等学校国語教育研究会西部支部研修会で「賀茂真淵の万葉主義」と題して講演を行った。",
    url: "",
    sdgs: "4"
  },
  {
    id: 4,
    facultyName: "川内 佑毅",
    department: "文学部 日本文学文化学科",
    title: "篆刻体験コーナー講師",
    role: "講師",
    type: "セミナー・ワークショップ",
    organizer: "全日本篆刻連盟",
    eventName: "篆刻体験コーナー",
    date: "5/19",
    location: "セントラルミュージアム銀座",
    target: "社会人・一般",
    summary: "文京区書道連盟主催の篆刻講習にて講師を務め、指導を行った。",
    url: "https://researchmap.jp/g0000220027/social_contribution/48442794",
    sdgs: "4"
  },
  {
    id: 5,
    facultyName: "川内 佑毅",
    department: "文学部 日本文学文化学科",
    title: "「わくわくワークショップ」アシスタント担当",
    role: "助言・指導",
    type: "セミナー・ワークショップ",
    organizer: "社団法人日展",
    eventName: "「わくわくワークショップ」",
    date: "11/10",
    location: "国立新美術館 三階講堂",
    target: "社会人・一般",
    summary: "社団法人日展主催の「わくわくワークショップ」にてアシスタントを担当し、助言・指導を行った。",
    url: "https://researchmap.jp/g0000220027/social_contribution/48442759",
    sdgs: "4"
  },
  {
    id: 6,
    facultyName: "大田 悦子",
    department: "文学部 英米文学科",
    title: "（青森県）進学力を高める高校支援事業",
    role: "助言・指導\n情報提供",
    type: "研究指導",
    organizer: "青森県立三本木高等学校",
    eventName: "（青森県）進学力を高める高校支援事業",
    date: "―",
    location: "青森県立三本木高等学校",
    target: "教育関係者",
    summary: "生徒の発信力強化のための英語指導力向上を目的に当該校で取り組んでいる英語授業指導改善研究会（年3回）に助言者として参加。7/5（オンライン）、10/24ー25 、2/４－5（＠三本木高校）計3回。",
    url: "",
    sdgs: "4"
  },
  {
    id: 7,
    facultyName: "大田 悦子",
    department: "文学部 英米文学科",
    title: "Sherpa (Senior High English Reform Project ALC)",
    role: "講師, 助言・指導, 企画等",
    type: "セミナー・ワークショップ",
    organizer: "株式会社アルク",
    eventName: "Sherpa Channel / セミナー",
    date: "2010/3-現在",
    location: "オンライン",
    target: "大学生, 教育関係者等",
    summary: "高校英語授業改善に貢献することを目的とした活動。教員向けのセミナーやYouTube配信「Sherpa Channel」を通じて指導法の提案等を行っている。",
    url: "https://alc-nds.com/ltaf/2021/09/20/sherpa/",
    sdgs: "4"
  },
  {
    id: 8,
    facultyName: "木下 聡",
    department: "文学部 史学科",
    title: "偉人・敗北からの教訓 シリーズ信長① 信長と斎藤道三・同盟の行方",
    role: "ＶＴＲ出演",
    type: "テレビ・ラジオ番組",
    organizer: "ＢＳ11",
    eventName: "偉人・敗北からの教訓 シリーズ信長① 信長と斎藤道三・同盟の行方",
    date: "4/20",
    location: "―",
    target: "小学生, 中学生, 高校生, 大学生, 大学院生, 教育関係者, 保護者, 研究者, 社会人・一般, メディア",
    summary: "偉人たちの「敗北」「失敗」から、学ぶべき教訓を探る番組にて専門的見地から解説を行った。",
    url: "https://topics.bs11.jp/ijin-haiboku-kyoukun_41/",
    sdgs: "4"
  },
  {
    id: 9,
    facultyName: "木下 聡",
    department: "文学部 史学科",
    title: "偉人・敗北からの教訓 太田道灌・文武両道の名将の最期",
    role: "ＶＴＲ出演",
    type: "テレビ・ラジオ番組",
    organizer: "ＢＳ11",
    eventName: "偉人・敗北からの教訓 太田道灌・文武両道の名将の最期",
    date: "9/28",
    location: "―",
    target: "小学生, 中学生, 高校生, 大学生, 大学院生, 教育関係者, 保護者, 研究者, 社会人・一般, メディア",
    summary: "偉人たちの「敗北」「失敗」から、学ぶべき教訓を探る番組にて専門的見地から解説を行った。",
    url: "https://topics.bs11.jp/ijin-haiboku-kyoukun_41/",
    sdgs: "4"
  },
  {
    id: 10,
    facultyName: "大江 啓賢",
    department: "文学部 教育学科",
    title: "学校研究",
    role: "講師, 助言・指導",
    type: "その他",
    organizer: "埼玉県立川島ひばりが丘特別支援学校",
    eventName: "埼玉県立川島ひばりが丘特別支援学校 学校研究",
    date: "2022/4/1～2025/3/31",
    location: "埼玉県立川島ひばりが丘特別支援学校",
    target: "教育関係者",
    summary: "実施主体が学校研究として行う研究授業について「授業の指導助言」および各教育課程のテーマに沿った「指導講評」を年間（年度内）3回実施した。",
    url: "",
    sdgs: "4"
  },
  {
    id: 11,
    facultyName: "大江 啓賢",
    department: "文学部 教育学科",
    title: "教育職員免許法認定講習",
    role: "講師",
    type: "資格認定講習",
    organizer: "埼玉県教育委員会",
    eventName: "教育職員免許法認定講習",
    date: "8/5-8/6, 12/26-12/27",
    location: "8月；埼玉県県民活動総合センター, 12月；埼玉県総合教育センター",
    target: "教育関係者",
    summary: "埼玉県教育委員会主催の「教育職員免許法認定講習」にて講師を担当した。",
    url: "",
    sdgs: "4"
  },
  {
    id: 12,
    facultyName: "大江 啓賢",
    department: "文学部 教育学科",
    title: "教育職員免許法認定講習",
    role: "講師",
    type: "資格認定講習",
    organizer: "さいたま市教育委員会",
    eventName: "教育職員免許法認定講習",
    date: "8/7-8/8",
    location: "さいたま市立さくら草特別支援学校",
    target: "教育関係者",
    summary: "さいたま市教育委員会主催の「教育職員免許法認定講習」にて講師を担当した。",
    url: "",
    sdgs: "4"
  },
  {
    id: 13,
    facultyName: "大江 啓賢",
    department: "文学部 教育学科",
    title: "幼稚園研修会講師",
    role: "講師",
    type: "その他",
    organizer: "学校法人細渕学園 まつもと幼稚園",
    eventName: "園内研修会",
    date: "7/10",
    location: "まつもと幼稚園",
    target: "教育関係者",
    summary: "まつもと幼稚園主催の園内研修会「幼稚園における発達障害幼児（ASD、ADHD等）の理解と対応」にて講師を担当した。",
    url: "",
    sdgs: "4"
  },
  {
    id: 14,
    facultyName: "大江 啓賢",
    department: "文学部 教育学科",
    title: "研修会講師",
    role: "講師",
    type: "その他",
    organizer: "日本特別支援教育オンライン学会",
    eventName: "会員向け専門研修会",
    date: "3/20",
    location: "オンライン",
    target: "学会会員, 教育・保育・福祉関係者",
    summary: "学会主催のオンラインによる専門研修会「肢体不自由児・病弱児の理解と支援」にて講師を担当した。",
    url: "",
    sdgs: "4"
  }
];