
import { Activity } from './types';

export const KENKYU_ASIA_CULT_DATA: Activity[] = [
  {
    id: 52,
    facultyName: "",
    department: "研究推進課",
    title: "国際シンポジウム「Muslim Philanthropy in Japan」",
    role: "出演, パネリスト, コメンテーター, 司会, 企画, 運営参加・支援",
    type: "セミナー・ワークショップ",
    organizer: "アジア文化研究所・研究所プロジェクト「公共社会学・人類学的視点からの在日ムスリムの多文化共生研究」（代表・子島進）",
    eventName: "国際シンポジウム「Muslim Philanthropy in Japan」",
    date: "6/2",
    location: "東洋大学白山キャンパススカイホール",
    target: "大学院生, 教育関係者, 研究者, 社会人・一般",
    summary: "Welcome Speech\nby Nobuo Misawa (Toyo University)\nPART I\nGeneral Introduction on Muslims in Japan\n(History and Background information)\nHirofumi Okai (Kyoto Sangyo University)\nDisaster Relief of the 2024 Noto Peninsula\nEarthquake by Mosques in Hokuriku Region\nHitomu Kotani (Tokyo Institute of Technology)\nMosque Activities during the\nin Osaka and Ebina\nPandemic\nMari Tamura (Oshin Dream Co., Ltd.)\n International Islamic Schools as Muslim Philanthropy\n(in near future)\nSusumu Nejima (Toyo University)\nPART II\nYamaoka Mitsutaro Becomes a Muslim:\nTime, Space, and Conversion in Imperial Japan\nMikiya Koyagi (UT-Austin)\nTaisho University's Social Services\n(Buddhist philanthropy in Japan)\nTomoaki Saito (Rinsho-ji Temple)\nPerception and Representation of \"Islamic Culture\"\nin Postwar and Post-9/11 Contemporary Japan\nYoko Yamashita (Yokohama National University)\nBeyond Embeddedness: Limits of New Economic\nSociology to Explain Muslim Altruism in Japan\nNaoto Higuchi & Mao Takahashi (Waseda University)\nUnderstanding Indonesian and Filipino Muslim Communities in Central Japan: A Comparative Perspective\nAnderson Villa (MSU-General Santos City)\nBetween Piety and Popularity: Muslim Experiences in\nShizuoka, Japan\nJohn Ostermiller (UN-Reno)\nMoving towards Multicultural Japan?: Muslims Students\nReligious Freedom in Japanese Public School Settings\nShino Yokotsuka (UMass-Boston)\nDiscussion and Concluding Remarks\nShariq Siddiqui\n(Muslim Philanthropy Initiative, Indiana University)",
    url: "https://sites.google.com/toyo.jp/acri/news_cr/20240602",
    sdgs: "3, 10"
  },
  {
    id: 53,
    facultyName: "",
    department: "研究推進課",
    title: "グローバル地中海映画上映会",
    role: "出演, パネリスト, コメンテーター, 司会, 企画, 運営参加・支援",
    type: "セミナー・ワークショップ",
    organizer: "アジア文化研究所（グローバル地中海地域研究拠点）",
    eventName: "第2回：トルコ映画『いとしのハニーちゃん』\n第3回：映像民族誌『ジプシー巡礼祭』\n第4回：スロヴェニア映画『ヴェスナ』\n第5回：ドイツ映画『はじめてのおもてなし』",
    date: "第2回：6/24, 第3回：7/18, 第4回：11/12, 第5回：12/5, 12/12",
    location: "東洋大学白山キャンパス 各教室",
    target: "大学生, 大学院生, 教育関係者, 研究者, 社会人・一般, 学術団体",
    summary: "第2回：『いとしのハニーちゃん』　1992年　95分　トルコ語〈日本語字幕〉\nあらすじ：西ドイツに渡り自動車整備工場で働いていたトルコ人青年は、ドイツ再統一を機に、貯金をはたいてメルセデス車を購入。故郷に錦を飾ろうと、愛車でトルコへの帰国を目指すが、帰郷の旅路で様々なトラブルに巻き込まれていく。コメディ・タッチで社会問題を描写する。\n解説：三沢伸生\n第3回：拠点構成員の左地亮子東洋大学准教授が昨年度の現地調査を基に製作した下記の映像作品の上映会を行いました。\n『ジプシー巡礼祭：More than One, Less than Many』　撮影・編集：左地亮子　2024年　50分　フランス語〈日本語字幕〉\nあらすじ：南仏カマルグ地方の町サント゠マリー゠ドゥ゠ラ゠メールで毎年５月に開催されるカトリック巡礼「ジプシー巡礼祭」には、フランス内外から多くのジプシーが参集する。2023年、巡礼祭のハイライトとなる聖サラの行列にあわせて、非ジプシーも含めた約4万人もの人びとがこの小さな町に集まった。\n解説：左地亮子\n第4回：『ヴェスナ (Vesna)』フランティシェク・チャープ監督　1953年　96分　スロヴェニア語＜日本語字幕〉\nあらすじ：社会主義期スロヴェニアを代表する恋愛コメディ映画。サモたち悪友 3 人組は、高校の数学試験の答案を手に入れるため、数学教師の娘と恋仲に求なるという陰謀を企てる。娘の本当の名前を知らない彼らは、春の女神にちなんで彼女をヴェスナと呼んでいた。数学教師の娘で魅力的なヤニャがサモとのデートに現れた時、二人は恋に落ちてしまう。\n司会：イェリサヴァ・ドボウシェク=セスナ（スロヴェニア・日本友の会）\n解説：アンドレイ・ベケシュ（リュブリャナ大学）\n第5回：『はじめてのおもてなし (Willkommen bei den Hartmanns)』サイモン・バーホーベン監督　2016年　116分　ドイツ語＜日本語字幕＞\nあらすじ：ミュンヘンの閑静な住宅街に暮らすハルトマン一家は、難民のディアロを受け入れる。文化の違いや習慣の違いによるハプニングの連続。彼を「おもてなし」するつもりだった、裕福だけれど壊れかけた一家は、彼との出会いをきっかけに、人生を見つめ直し、生きる喜びを取り戻していく。2016年度ドイツ映画興行収入No.1作品。\n※上映にあたり、作品上映当時のドイツの状況やドイツの移民難民受け入れの歴史について解説します。\n12月19日（木）には、本作日本語字幕を担当した吉川美奈子さんに、この作品をはじめとするドイツ映画を手がかりに、映画から読み取ることができるドイツ社会の様相と、社会状況とともに変化する作品解釈についてお話いただきます。",
    url: "https://sites.google.com/toyo.jp/globalmediterranean/activities/240624filmscreening",
    sdgs: "4, 5, 10, 11, 16, 17"
  },
  {
    id: 54,
    facultyName: "",
    department: "研究推進課",
    title: "第1回 アジア文化研究所 研究例会",
    role: "出演, パネリスト, 司会, 講師, 助言・指導, 企画, 運営参加・支援",
    type: "講演会",
    organizer: "アジア文化研究所・研究所プロジェクト「アジアインフラ投資銀行(AIIB)による投資とアジア諸国における政治・経済企業法制の変容」（代表・後藤武秀）ほか",
    eventName: "研究例会　米中対立下における中国企業の最新動向",
    date: "7/29",
    location: "東洋大学白山キャンパススカイホール",
    target: "大学生, 大学院生, 教育関係者, 研究者, 社会人・一般, 学術団体",
    summary: "報告\n報告者:杜進\n(拓殖大学名誉教授・アジア文化研究所客員研究員)\n「中国企業のイノベーション活動: 現地調査から得た知見」\nコメンテーター:羅歓鎮\n(東京経済大学教授・アジア文化研究所客員研究員)\n\n報告2\n報告者:薛軍\n(南開大学経済学部教授・アジア文化研究所客員研究員)\n「民営企業の対外投資の動向:一帯一路構想との関連を中心に」\nコメンテーター:楊起中\n(経済学部准教授・アジア文化研究所研究員)",
    url: "https://sites.google.com/toyo.jp/acri/news_cr/20240729",
    sdgs: "4, 8, 9"
  },
  {
    id: 55,
    facultyName: "",
    department: "研究推進課",
    title: "東洋大学アジア文化研究所井上助成　子島プロジェクト",
    role: "出演, パネリスト, コメンテーター, 司会, 企画, 運営参加・支援",
    type: "セミナー・ワークショップ",
    organizer: "アジア文化研究所・研究所プロジェクト「公共社会学・人類学的視点からの在日ムスリムの多文化共生研究」（代表・子島進）",
    eventName: "「Broadening Our Horizons \"The 4th Workshop on International Islamic schools in Japan\"」",
    date: "9/15",
    location: "東洋大学白山キャンパス10号館1階　A102",
    target: "大学生, 大学院生, 教育関係者, 研究者",
    summary: "Morning Presentations\n\nIntroduction of Islamic Schools \nInternational Islamia School Otsuka by Hussam Zaineh (Principal, 11S0) \nSapporo International School by Mohamed Shehata (Principal, SIS) \nYUAI International Islamic School by Yousry Elhamzawi(Vice Principal, YUAI) \nFukuoka International Islamic School by Mohamed Hassan (General Manager, FIIS) \nTokyo lqra International School by Mohammad Zakir Rossen (Head of \nSchool Administration, IQRA) \nBritish International School by Hafiz Salman Thanvi (Principal, BIS) \n\nAcculturation and Ethnic Identity of Second-Generation \nImmigrants in Japan by Nukaga Misako (Professor, Tokyo University) \n\nAfternoon Presentations\nExperiences of Indian International Schools \nby Yogendra Puranik (Principal, Tsuchiura First High School\n\nDiscussion (with Tea Break) \n\nConcluding Remarks by Nejima Susumu ",
    url: "https://sites.google.com/toyo.jp/acri/news_cr/20240915",
    sdgs: "4, 10"
  },
  {
    id: 56,
    facultyName: "",
    department: "研究推進課",
    title: "アジア文化研究所　公開シンポジウム",
    role: "出演, パネリスト, コメンテーター, 司会, 企画, 運営参加・支援",
    type: "セミナー・ワークショップ",
    organizer: "アジア文化研究所",
    eventName: "公開シンポジウム「多文化アジアにおける異文化接触：日中異文化接触と教育の課題」",
    date: "10/12",
    location: "東洋大学白山キャンパス第一会議室、オンライン",
    target: "大学生, 大学院生, 教育関係者, 研究者, 社会人・一般, 学術団体",
    summary: "企画趣旨\n\n東アジアにおける異文化接触の歴史を振り返りつつ、異文化接触が個人および社会に及ぼす意味と可能性をさぐる。また本研究所と華中科技大学との交流の歴史は20年以上におよんでおり、そのことの意義と今後の展望についても考える。　　　　　　　　　　　　　　　　　　　　　　　　　野間信幸（文学部名誉教授、アジア文化研究所客員研究員）\n「井上円了の台湾異文化体験」\n井上貴也（法学部教授、アジア文化研究所研究員）\n「日中企業の異文化接触について」\n王閏梅（華中科技大学日本語科副教授、アジア文化研究所客員研究員）\n「中国における大学日本語教育の危機と展望」　　　　　　　　　　　　野間信幸（文学部名誉教授、アジア文化研究所客員研究員）\n「華中科技大学との交流に関する資料提供（初稿）」\n子島進（国際学部教授、アジア文化研究所研究員）\n「日本文化の紹介方法について考える\nーオンライン講義による華中科技大学生との交流から一」\nコメンテーター：王浄華・王競超・黄均鉤・拘子刊・陳玲\n（いずれも華中科技大学からのオンライン参加）",
    url: "https://sites.google.com/toyo.jp/acri/news_cr/20241012",
    sdgs: "4, 10"
  },
  {
    id: 57,
    facultyName: "",
    department: "研究推進課",
    title: "グローバル地中海 特別ワークショップ",
    role: "出演, パネリスト, コメンテーター, 司会, 企画, 運営参加・支援",
    type: "セミナー・ワークショップ",
    organizer: "人間文化研究機構グローバル地域研究推進事業グローバル地中海地域研究東洋大学アジア文化研究所拠点",
    eventName: "「表出するマージナリティ: 映像に見るヨーロッパと中央アジアの非日常のパフォーマンス」",
    date: "11/9",
    location: "東洋大学白山キャンパス125記念ホール",
    target: "大学生, 大学院生, 教育関係者, 研究者, 社会人・一般",
    summary: "グローバル地中海地域研究東洋大学アジア文化研究所拠点は、映像人類学の特別ワークショップ「表出するマージナリティ――映像に見るヨーロッパと中央アジアの非日常のパフォーマンス」を開催いたしました。本ワークショップでは、当拠点のメンバーである久野聖子（同志社大学）と左地亮子（東洋大学）が、それぞれ昨年度の調査において撮影した映像をもとにした映像民族誌を上映しました。それに対し、竹中宏子（早稲田大学）がヨーロッパ研究の観点から、和崎聖日（中部大学）が映像人類学の観点からコメントを行い、また、東京ドキュメンタリー映画祭2022、Ethnografilm Paris 2023などに入選した和崎や木村暁（東京外国語大学）らの共同制作による民族誌映画を特別上映しました。\n\n今回上映する３作品のうち、ふたつはスペインおよびフランスのジプシー・コミュニティーの祝祭を、ひとつはウズベキスタンの女性霊媒による治療儀礼を扱うものです。可視と不可視の位相を転覆し撹乱する非日常のパフォーマンスを介して、歴史的に社会の周縁に置かれてきた存在が現出すること、その様子を映像という手法によって表象することの意味が問われました。",
    url: "https://sites.google.com/toyo.jp/acri/news_cr/20241109",
    sdgs: "4, 10"
  },
  {
    id: 58,
    facultyName: "",
    department: "研究推進課",
    title: "東洋大学アジア文化研究所・復旦大学発展研究院 共催 国際シンポジウム",
    role: "出演, パネリスト, コメンテーター, 司会, 講師, 企画",
    type: "講演会",
    organizer: "東洋大学アジア文化研究所・復旦大学発展研究院 共催",
    eventName: "国際シンポジウム「日中における経済発展と金融政策」",
    date: "11/15",
    location: "東洋大学白山キャンパス井上円了ホール",
    target: "大学生, 大学院生, 教育関係者, 研究者, 社会人・一般",
    summary: "本シンポジウムは、日本と中国の経済政策及び金融政策を基本課題とするものであります。\n\nポスター本企画の立案は、復旦大学発展研究院金融研究センター所長の孫立堅教授はじめ、楊秋怡所長補佐らのご尽力になるものであり、深く感謝申し上げます。同時に、本企画は、東洋大学アジア文化研究所で10数年来継続してきました、中国の一帯一路政策並びに途上国のインフラ建設のために設立されたアジアインフラ投資銀行(略称AIIB)に関する共同研究の趣旨に沿うものであることから、ここに、共同開催という形で広く研究成果を世に問うこととなりました。今日、日中間には様々な問題があろうかと思います。しかし、それを乗り越えながら、多数の日本企業が中国で経済活動を展開しております。本日の発表の成果は、こうした企業、さらには今後、中国との間で経済活動を展開しようとしている企業にとっても有益な視点を提供するものと確信しております。",
    url: "https://sites.google.com/toyo.jp/acri/news_cr/20241115",
    sdgs: "4, 8, 9"
  },
  {
    id: 59,
    facultyName: "",
    department: "研究推進課",
    title: "国際シンポジウム「The Echoes of the Narrow Victory over the Russo-Japanese War」",
    role: "出演, パネリスト, コメンテーター, 司会, 講師, 企画",
    type: "講演会",
    organizer: "東洋大学アジア文化研究所2024年度特別措置予算ほか",
    eventName: "International Symposium \"The Echoes of the Narrow Victory over the Russo-Japanese War\"",
    date: "12/7",
    location: "東洋大学白山キャンパススカイホール",
    target: "大学生, 大学院生, 教育関係者, 研究者, 社会人・一般, 学術団体",
    summary: "東洋大学アジア文化研究所と人間文化研究機構グローバル地域研究推進事業グローバル地中海地域研究東洋大学アジア文化研究所拠点は、国際シンポジウム「日露戦争”辛勝”の残響」共同開催いたしました。\n\n　2024年は日露戦争開戦の年から120年にあたります。ロシア革命の勃発とアメリカの仲介により、日本は辛くも勝利を手にしましたが、このことは、列強の支配下におかれた世界中の人々に独立への希望を与えることにもなりました。日本の辛勝を受け、各地で多くの著作が編まれると同時に、出身地の内外で独立運動を活発化させる人々が現れました。\n\n　本シンポジウムでは、日露戦争の辛勝の残響として、イスラーム圏の三つの地域の史料に見られるこのような反応に光が当てられました。世界情勢がますます混迷を極める現在の視点から、日本の勝利という歴史的事件がその後のグローバルヒストリーにあたえた影響を振り返りました。",
    url: "https://sites.google.com/toyo.jp/globalmediterranean/activities/231207echoesofvictory",
    sdgs: "1, 10, 16"
  },
  {
    id: 60,
    facultyName: "",
    department: "研究推進課",
    title: "アジア文化研究所、白山人類学研究　共催フォーラム",
    role: "出演, パネリスト, コメンテーター, 司会, 講師, 企画",
    type: "セミナー・ワークショップ",
    organizer: "アジア文化研究所、白山人類学会、科研費基盤研究プロジェクトほか",
    eventName: "第16回フォーラム「みえない移民労働者――日本・台湾に生きるインドネシア人と共生の諸相」",
    date: "12/21",
    location: "東洋大学白山キャンパススカイホール、オンライン",
    target: "大学生, 大学院生, 教育関係者, 研究者, 社会人・一般, 学術団体",
    summary: "趣旨\n日本と台湾は、1990年代以来、労働力不足や少子高齢化を背景に、海外から多数の移民労働者を受け入れてきた。2023年、移民労働者の人口は、台湾では総就労人口の6.1パーセントを、日本では同3.4パーセントを占めるまでになっている。本フォーラムでは、これら移民労働者のうちインドネシア人に焦点をおき、かれらと地域社会との関係を、日常生活における共生（ないし非共生）という視点から探り、また比較検討する。\n　インドネシア人移民労働者は、日本では約12万人、台湾では約27万人を数える（2023）年。多くは、製造業、建設業、農業漁業等の非熟練労働部門で働いている。両国に共通する特徴としては、かれらが漁業部門の移民労働者の圧倒的多数を占めることがあげられる。これらインドネシア人移民労働者は、職場を離れて地域社会の人びとと直接、交流することはほとんどない。とりわけ漁業のように船上を職場、宿舎とするインドネシア人は、ほとんど地域社会との接点がないといといってもよい。\n　こうした「みえない存在」になっているインドネシア人移民労働者は、就労地でいかに自らの生活世界をつくっているのか、そこでホスト社会とどのように結びついているのか、またホスト社会はかれらにどう働きかけ、包摂しようとしているのか——本フォーラムでは、日台両国におけるインドネシア人移民労働と地域社会との日常生活レベルでの関わりの諸相を、フィールドでの具体的事例によりながら提示し、そこにみられる共生（ないし非共生）の地域性および共通性を検討していく。",
    url: "https://www.toyo.ac.jp/news/20241217-16648.html",
    sdgs: "4, 8, 17"
  }
];
