import { Activity } from './types';

export const PHILOSOPHY_DATA: Activity[] = [
  {
    id: 160,
    facultyName: "",
    department: "井上円了哲学センター",
    title: "井上円了記念博物館 常設展示",
    role: "情報提供, 企画, その他",
    type: "施設一般公開",
    organizer: "井上円了哲学センター",
    eventName: "井上円了記念博物館 常設展示",
    date: "4/1-3/31",
    location: "東洋大学井上円了記念博物館",
    target: "小学生, 中学生, 高校生, 大学生, 社会人・一般等",
    summary: "「井上円了 その生涯と教育活動」のテーマのもと、生い立ちから哲学館の創立、社会教育への挑戦、晩年の活動までを紹介。2015年にオープンした「塩川正十郎記念展示コーナー」も併設し、本学の原点と理念への理解を深める機会を提供しています。",
    url: "https://sites.google.com/toyo.jp/iecp-museum/permanent",
    sdgs: "4"
  },
  {
    id: 161,
    facultyName: "",
    department: "井上円了哲学センター",
    title: "井上円了考案ボードゲーム「哲学飛将碁」の解説動画、Webページ公開",
    role: "助言・指導, 情報提供, 企画, 運営参加・支援, 実演, その他",
    type: "インターネット",
    organizer: "井上円了哲学センター",
    eventName: "哲学飛将碁の解説公開",
    date: "2023/4/3-現在まで",
    location: "YouTube「東洋大学 toyouniv」、Web page",
    target: "中学生, 高校生, 大学生, 一般等",
    summary: "井上円了が哲学教育のために作成したボードゲーム「哲学飛将碁」の解説動画とWebページを公開。天理大学・岡田正彦教授や本学経営学部・関勝寿教授、将棋研究会の学生が登場し、ルールや面白さを伝えています。",
    url: "https://sites.google.com/toyo.jp/iecp-game",
    sdgs: "4"
  },
  {
    id: 162,
    facultyName: "",
    department: "井上円了哲学センター",
    title: "特別展「鉄道は哲学者を乗せてゆく」図録公開",
    role: "情報提供, 寄稿, その他",
    type: "インターネット",
    organizer: "井上円了哲学センター",
    eventName: "図録のWeb公開",
    date: "2023/4/5-現在まで",
    location: "Web page",
    target: "中学生, 高校生, 大学生, 一般等",
    summary: "2022年に開催した鉄道開業150周年記念特別展「鉄道は哲学者を乗せてゆく―東洋大学創立者・井上円了の講演旅行―」の図録を公開。学芸員による解説と研究員の研究成果が一冊にまとまっています。",
    url: "https://www.toyo.ac.jp/news/about_founder_iecp_social-partnership_museum_20230404.html",
    sdgs: "4"
  },
  {
    id: 163,
    facultyName: "",
    department: "井上円了哲学センター",
    title: "湯本豪一記念日本妖怪博物館への井上円了写真提供",
    role: "情報提供, その他",
    type: "その他",
    organizer: "湯本豪一記念日本妖怪博物館（三次もののけミュージアム）",
    eventName: "妖怪博物館常設展",
    date: "5/9-8/27",
    location: "湯本豪一記念日本妖怪博物館",
    target: "行政機関",
    summary: "広島県三次市の妖怪博物館の常設展にて、井上円了の書幅「妖怪の正体見れば我こころ」を出品。作品とともに井上円了の顔写真を提供し展示されました。",
    url: "https://miyoshi-mononoke.jp/",
    sdgs: "4"
  },
  {
    id: 164,
    facultyName: "",
    department: "井上円了哲学センター",
    title: "『東洋大学百年史』の電子ブック化",
    role: "情報提供, その他",
    type: "インターネット",
    organizer: "井上円了哲学センター",
    eventName: "百年史電子ブック化",
    date: "5/30-現在まで",
    location: "百年史電子ブック",
    target: "メディア",
    summary: "1993年から1995年に発行された全8編の東洋大学史の記録のうち、「通史編 I」「通史編Ⅱ」を電子ブック化し公開しました。",
    url: "https://sites.google.com/toyo.jp/iecp-oshirase/東洋大学百年史を電子ブック化",
    sdgs: "4"
  },
  {
    id: 165,
    facultyName: "",
    department: "井上円了哲学センター",
    title: "東洋大学史ブックレット全15巻をWeb公開",
    role: "情報提供, その他",
    type: "インターネット",
    organizer: "井上円了哲学センター",
    eventName: "ブックレットのWeb公開",
    date: "2023/5/29-現在まで",
    location: "東洋大学史ブックレット",
    target: "中学生, 高校生, 大学生, 一般等",
    summary: "創立125周年に制作した、井上円了や大学史を分かり易く紹介したブックレット全15巻を公開。先人たちの情熱や大学の歩みを感じられる資料です。",
    url: "https://sites.google.com/toyo.jp/iecp-publication/publications/centerpub/Toyo-University-history-booklet",
    sdgs: "4"
  },
  {
    id: 166,
    facultyName: "",
    department: "井上円了哲学センター",
    title: "東洋大学京北高等学校「学祖の日」講演",
    role: "講師",
    type: "講演会",
    organizer: "東洋大学京北高等学校、井上円了哲学センター",
    eventName: "学祖の日",
    date: "6/1",
    location: "東洋大学京北高等学校",
    target: "高校生",
    summary: "1年生を対象に井上円了の生い立ちや功績について北田学芸員が講演。豊富な資料画像を用いて、彼が遺した博物館資料や妖怪研究について紹介しました。",
    url: "https://sites.google.com/toyo.jp/iecp-oshirase/20240601",
    sdgs: "4"
  },
  {
    id: 167,
    facultyName: "",
    department: "井上円了哲学センター",
    title: "越路円了会創立35周年記念「井上円了文化講演会」",
    role: "講師, 情報提供, 企画, 運営参加・支援, 実演",
    type: "講演会",
    organizer: "越路円了会、東洋大学井上円了哲学センター",
    eventName: "井上円了文化講演会",
    date: "6/2",
    location: "越路総合福祉センター",
    target: "中学生, 高校生, 大学生, 一般等",
    summary: "法学部長谷川琢哉教授が「マンガ『円了』に描かれた長岡」と題して講演。円了が長岡で過ごした少年期・青年期を、制作中のマンガのシーンを交えて詳細に解説しました。",
    url: "https://sites.google.com/toyo.jp/iecp-oshirase/越路円了会文化講演会報告",
    sdgs: "4"
  },
  {
    id: 168,
    facultyName: "",
    department: "井上円了哲学センター",
    title: "新潟県長岡市立越路小学校 円了学習",
    role: "講師, 助言・指導, 企画, 運営参加・支援, 実演, その他",
    type: "講演会",
    organizer: "井上円了哲学センター",
    eventName: "越路小in東洋大学 2024年度",
    date: "7/4",
    location: "東洋大学白山キャンパス",
    target: "小学生",
    summary: "円了の生誕地である越路小学校の6年生102名が来校。学長の歓迎挨拶、白山グリークラブの合唱披露に続き、長谷川教授による「井上円了と哲学を学ぶ理由」の講話を実施。博物館見学や像の前での写真撮影を通じ、郷土の偉人への理解を深めました。",
    url: "https://sites.google.com/toyo.jp/iecp-oshirase/越路小学校校外学習報告",
    sdgs: "4"
  },
  {
    id: 169,
    facultyName: "",
    department: "井上円了哲学センター",
    title: "特別展「おばけと円了ー季節はずれの幽霊画展ー」",
    role: "情報提供, 企画, その他",
    type: "施設一般公開",
    organizer: "井上円了記念博物館",
    eventName: "幽霊画展",
    date: "10/15-12/21",
    location: "東洋大学井上円了記念博物館",
    target: "小学生, 中学生, 高校生, 大学生, 一般等",
    summary: "円了が「妖怪」と呼び研究対象とした、不思議な存在としての「おばけ」に焦点を当て、彼が収集した幽霊画を展示。円了がおばけとどう対峙したかを検証する内容です。",
    url: "https://sites.google.com/toyo.jp/iecp-museum/special/20241015",
    sdgs: "4"
  },
  {
    id: 170,
    facultyName: "",
    department: "井上円了哲学センター",
    title: "マンガ「円了」展 －哲学者の胎動－",
    role: "情報提供, 企画, その他",
    type: "施設一般公開",
    organizer: "井上円了哲学センター",
    eventName: "マンガ「円了」展",
    date: "10/28-12/16",
    location: "東洋大学白山キャンパス 5号館1階",
    target: "小学生, 中学生, 高校生, 大学生, 一般等",
    summary: "円了の青春時代を描いたマンガの制作資料やインタビュー、解説パネルを展示。激動の明治を生きた一人の青年の思索の軌跡を、マンガならではの表現で紹介しています。",
    url: "https://sites.google.com/toyo.jp/iecp-manga/manga/マンガ円了展",
    sdgs: "4"
  },
  {
    id: 171,
    facultyName: "",
    department: "井上円了哲学センター",
    title: "2024年度哲学堂祭を挙行",
    role: "講師, その他",
    type: "フェスティバル",
    organizer: "井上円了哲学センター",
    eventName: "2024年度哲学堂祭",
    date: "11/2",
    location: "蓮華寺、哲学堂公園",
    target: "幼稚園以下, 小学生, 中学生, 大学生, 一般等",
    summary: "円了の遺言に基づき毎年11月第1土曜日に開催。墓前祭に続き哲学堂公園で記念講演会を実施。円了が定めた「四聖」を毎年順に取り上げ、参列者には遺言通り甘酒や珈琲が振る舞われました。",
    url: "https://www.toyo.ac.jp/news/20241105-16173.html",
    sdgs: "該当なし"
  },
  {
    id: 172,
    facultyName: "",
    department: "井上円了哲学センター",
    title: "「井上円了が志したものとは」作品募集",
    role: "編集, 企画, その他",
    type: "その他",
    organizer: "井上円了哲学センター",
    eventName: "2024年度「井上円了が志したものとは」作品募集",
    date: "4/27-7/15",
    location: "全国公募",
    target: "高校生, 大学生, 大学院生, 社会人・一般",
    summary: "井上円了の教育理念を探究し、それを現在の自らの生き方にいかに活かしていくかを文章にまとめた作品を募集。若者の志を育む機会を提供しています。",
    url: "https://sites.google.com/toyo.jp/iecp-edu/KOKOROZASHITAMONO",
    sdgs: "4"
  },
  {
    id: 173,
    facultyName: "",
    department: "井上円了哲学センター",
    title: "創立者・井上円了先生の人生を綴った：マンガ『円了』",
    role: "編集, 情報提供, 企画, 寄稿, その他",
    type: "インターネット",
    organizer: "井上円了哲学センター",
    eventName: "マンガ『円了』の配信",
    date: "2023/4/1-2025/2/7",
    location: "オンライン公開",
    target: "小学生, 中学生, 高校生, 大学生, 一般等",
    summary: "日本の哲学の先駆けであり教育者・仏教者でもあった円了の人生をマンガ化。チャレンジ精神を持って生きた姿を描き、若年層にも親しみやすく功績を伝えています。",
    url: "https://sites.google.com/toyo.jp/iecp-manga",
    sdgs: "4"
  },
  {
    id: 174,
    facultyName: "",
    department: "井上円了哲学センター",
    title: "哲学堂公園の歩き方－井上円了が教える心を磨く精神修養－",
    role: "講師, 助言・指導, 情報提供, 企画, 実演",
    type: "インターネット",
    organizer: "井上円了哲学センター",
    eventName: "Web動画配信",
    date: "2024/2/26-現在まで",
    location: "YouTube、Web page",
    target: "小学生, 中学生, 高校生, 大学生, 一般等",
    summary: "精神修養的公園として設計された哲学堂公園の正しい順路と意味を動画で解説。長谷川教授の案内により、哲学的概念を初学者にも分かりやすく伝えています。",
    url: "https://sites.google.com/toyo.jp/iecp-socialpartnership/tetsugakudo",
    sdgs: "4, 11"
  },
  {
    id: 175,
    facultyName: "",
    department: "井上円了哲学センター",
    title: "『CATALOG 井上円了』Web公開",
    role: "情報提供, その他",
    type: "インターネット",
    organizer: "井上円了哲学センター",
    eventName: "記念図録の公開",
    date: "2023/12/15-現在まで",
    location: "Web公開",
    target: "中学生, 高校生, 大学生, 一般等",
    summary: "井上円了没後100周年記念図録。選別された関連資料を幅広い分野の研究者が解説した貴重な資料です。",
    url: "https://sites.google.com/toyo.jp/iecp-publication/publications/centerpub/CATALOG",
    sdgs: "4"
  }
];