import { Activity } from './types';

export const KENKYU_INDUSTRIAL_DATA: Activity[] = [
  {
    id: 62,
    facultyName: "",
    department: "研究推進課",
    title: "企業技術相談",
    role: "助言・指導",
    type: "その他",
    organizer: "工業技術研究所",
    eventName: "技術相談窓口",
    date: "通年",
    location: "工業技術研究所・Web",
    target: "企業, 行政機関",
    summary: "企業からの技術的課題に対し、最適な研究者の選定とマッチングを行い、解決に向けた無料相談を実施。",
    url: "https://www.toyo.ac.jp/research/labo_center/riit/",
    sdgs: "9"
  },
  {
    id: 63,
    facultyName: "",
    department: "研究推進課",
    title: "第5回 水のシンポジウム",
    role: "パネリスト, 講師",
    type: "講演会",
    organizer: "工業技術研究所・水環境改善技術研究会",
    eventName: "東洋大学重点研究推進プログラム『安心な水を未来へ』",
    date: "11/16",
    location: "川越キャンパス・オンライン",
    target: "研究者, 企業, 行政機関",
    summary: "「新しい排水処理技術の評価と社会実装に向けて」をテーマに、2022年度からの重点研究プロジェクトの成果を発表。",
    url: "https://www.toyo.ac.jp/news/20241015-15810.html",
    sdgs: "6, 14"
  },
  {
    id: 64,
    facultyName: "",
    department: "研究推進課",
    title: "空き家問題への処方箋 講演会",
    role: "コメンテーター, 講師",
    type: "講演会",
    organizer: "工業技術研究所（飯能信用金庫共催）",
    eventName: "解決策を現状・各種制度・改善実例から考える",
    date: "2/21",
    location: "川越キャンパス 第1会議室",
    target: "社会人・一般, 企業, 行政機関",
    summary: "地域社会の課題である空き家問題について、法制度や具体的な改善事例、産官学連携の視点から解決策を提示。",
    url: "https://www.toyo.ac.jp/news/20250129-16883.html",
    sdgs: "9"
  },
  {
    id: 65,
    facultyName: "",
    department: "研究推進課",
    title: "工業技術研究所 研究発表会",
    role: "講師, 運営",
    type: "講演会",
    organizer: "工業技術研究所",
    eventName: "オンライン研究発表会 2024",
    date: "2/21-3/7",
    location: "オンライン特設サイト",
    target: "企業, 行政機関, 学生",
    summary: "研究員および学生による38件の研究成果をオンラインポスター形式で公開し、産学連携の推進を図る。",
    url: "https://sites.google.com/toyo.jp/riit/news/2025-02-04",
    sdgs: "9"
  },
  {
    id: 66,
    facultyName: "",
    department: "研究推進課",
    title: "デジタルエンジニアリングアカデミー",
    role: "講師, 助言・指導",
    type: "セミナー・ワークショップ",
    organizer: "工業技術研究所・武蔵野銀行",
    eventName: "工場のＩｏＴ化からＤＸ化に向けて",
    date: "5/15-11/20",
    location: "川越キャンパスほか",
    target: "企業",
    summary: "中小企業のDX推進を支援するため、IoT技術の自社導入を目指す連続講座を実施。実習や工場見学を通じた伴走支援を行う。",
    url: "―",
    sdgs: "9"
  },
  {
    id: 67,
    facultyName: "",
    department: "研究推進課",
    title: "「越生梅林エスティ」開発秘話講演",
    role: "講師",
    type: "講演会",
    organizer: "TSO International（国際発酵・醸造食品産業展）",
    eventName: "キャンパス内に自生する花から分離した酵母で日本酒造り",
    date: "7/30",
    location: "東京ビッグサイト",
    target: "企業, 研究者, 一般",
    summary: "産学連携による地域特産物の高付加価値化事例として、独自酵母を用いた日本酒開発のプロセスと成果を外部展示会で発表。",
    url: "https://toyobioresilience.jp/blog/2024-07-302.html",
    sdgs: "4, 9"
  }
];
