import { Activity } from './types';

export const SPORTS_DATA: Activity[] = [
  {
    id: 176,
    facultyName: "",
    department: "TOYOスポーツセンター",
    title: "東京都北区を盛り上げるバスケ対抗戦「THE NORTH TOKYO DERBY」",
    role: "助言・指導, 企画, 運営参加・支援, 実演, その他",
    type: "施設一般公開",
    organizer: "TOYOスポーツセンター、城北信用金庫等共催",
    eventName: "THE NORTH TOKYO DERBY",
    date: "7/21",
    location: "東洋大学赤羽台キャンパス HELSPO HUB-3 アリーナ",
    target: "幼稚園以下, 小学生, 中学生, 社会人・一般, 北区住民等",
    summary: "北区にキャンパスを置く本学バスケットボール部と、東京成徳大学の対抗戦を学生が企画運営。試合に加え、地域のキッズチアダンス披露や「バスケットボール体験教室」を実施。1対1の技術指導やダンクシュートの披露で地域の子どもたちにスポーツの魅力を伝えました。",
    url: "https://www.toyo.ac.jp/news/20240730-15115.html",
    sdgs: "3, 4, 11, 17"
  },
  {
    id: 177,
    facultyName: "",
    department: "TOYOスポーツセンター",
    title: "サッカー教室「TOYO UNIV SOCCER CLINIC in ASAKA」",
    role: "講師, 助言・指導, 企画, 運営参加・支援, 実演",
    type: "セミナー・ワークショップ",
    organizer: "主催：サッカー部男子・女子、後援：朝霞市",
    eventName: "サッカー教室 in ASAKA",
    date: "11/9",
    location: "東洋大学朝霞キャンパス サッカーグラウンド",
    target: "小学生, 保護者, 行政機関",
    summary: "次世代の育成を目的に朝霞市在住の小学生約60名を対象に開催。ドリブルやシュート練習、ミニゲームを実施したほか、公式戦でのエスコートキッズも体験。スポーツを通じた地域交流を行いました。",
    url: "https://toyo-footballclub.jp/mens/",
    sdgs: "4, 11, 16, 17"
  },
  {
    id: 178,
    facultyName: "",
    department: "TOYOスポーツセンター",
    title: "【硬式野球部】「第2回ベースボールクリニック in 川越」",
    role: "講師, 助言・指導, 企画, 運営参加・支援, 実演",
    type: "セミナー・ワークショップ",
    organizer: "硬式野球部",
    eventName: "ベースボールクリニック in 川越",
    date: "12/7",
    location: "東洋大学川越キャンパス野球場",
    target: "小学生, 保護者, 行政機関, メディア",
    summary: "川越・鶴ヶ島市の小学生285名が参加。ドラフト指名を受けた一條・岩崎両選手も参加し、技術指導やデモンストレーションを実施。将来の野球人育成と地域連携を推進しました。",
    url: "https://www.toyo.ac.jp/news/20241209-16574.html",
    sdgs: "4, 11, 16, 17"
  },
  {
    id: 179,
    facultyName: "",
    department: "TOYOスポーツセンター",
    title: "バスケットボール教室「TOYO UNIV basketball Academy2024」",
    role: "講師, 助言・指導, 企画, 運営参加・支援, 実演",
    type: "セミナー・ワークショップ",
    organizer: "主催：バスケットボール部女子、後援：東京都北区等",
    eventName: "TOYO UNIV basketball Academy2024",
    date: "11/9-2/23 (全8回)",
    location: "東洋大学赤羽台キャンパス",
    target: "小学生, 中学生, 行政機関",
    summary: "北区および連盟の後援を得て、全8回にわたり地域の子どもたちへバスケットボール指導を実施。基本技術から実戦練習まで幅広く学びました。",
    url: "https://www.toyo.ac.jp/news/20241018-15934.html",
    sdgs: "3, 11, 16, 17"
  },
  {
    id: 180,
    facultyName: "",
    department: "TOYOスポーツセンター",
    title: "田中映伍選手が茅ケ崎市立松林中学校で講演会",
    role: "講師",
    type: "講演会",
    organizer: "茅ケ崎市立松林中学校",
    eventName: "松林中学校講演会",
    date: "11/27",
    location: "茅ケ崎市立松林中学校",
    target: "中学生, 教育関係者",
    summary: "パリパラリンピック競泳出場の田中映伍選手（福祉社会デザイン学部2年）が地元の中学校で「両腕がないことを武器に」と題して講演。自身の生い立ちや水泳への情熱、パラリンピックでの経験を語り、足でペットボトルの水を飲むデモンストレーション等で生徒たちに深い感銘を与えました。",
    url: "https://www.toyo.ac.jp/news/20241129-16447.html",
    sdgs: "4"
  },
  {
    id: 181,
    facultyName: "",
    department: "TOYOスポーツセンター",
    title: "シンポジウム「共生と保育」",
    role: "出演, パネリスト, 司会, 講師, 助言・指導, 企画等",
    type: "講演会",
    organizer: "主催：TOYOスポーツセンター、共催：日本パラ水泳連盟",
    eventName: "「共生と保育～パラスイマーとの交流保育実践より～」",
    date: "3/3",
    location: "東洋大学赤羽台キャンパス、オンライン",
    target: "教育関係者, 保護者, 研究者, 社会人・一般等",
    summary: "本学と日本パラ水泳連盟の連携協定に基づき、嶋﨑博嗣教授を中心に実施された「幼児とパラスイマーとの交流保育」を振り返るシンポジウム。パラスイマーの田中映伍選手ら、保育士、保護者、学生、教員がそれぞれの立場から成果を報告し、共生社会の実現に向けた知見を共有しました。",
    url: "https://www.toyo.ac.jp/news/20250312-17157.html",
    sdgs: "4, 11"
  },
  {
    id: 182,
    facultyName: "",
    department: "TOYOスポーツセンター",
    title: "【ラグビー部】第二回東洋大学杯 ラグビー地域対抗戦",
    role: "講師, 助言・指導, 企画, 運営参加・支援",
    type: "セミナー・ワークショップ",
    organizer: "ラグビー部",
    eventName: "第二回東洋大学杯 ラグビー地域対抗戦",
    date: "2/23",
    location: "東洋大学川越キャンパスラグビー場",
    target: "小学生",
    summary: "川越、深谷、狭山ラグビースクールによる小学生向けの対抗戦を実施。約200名の小学生とラグビー部員が共に汗を流し、競技の普及と地域交流を図りました。",
    url: "https://toyorugby.com/",
    sdgs: "4, 11"
  },
  {
    id: 183,
    facultyName: "",
    department: "TOYOスポーツセンター",
    title: "【陸上競技部】鹿島市にて陸上教室開催",
    role: "企画, 運営参加・支援, 実演, その他",
    type: "セミナー・ワークショップ",
    organizer: "鹿島市生涯学習課",
    eventName: "東洋大学の皆さんとの陸上教室",
    date: "2/22",
    location: "鹿島市陸上競技場",
    target: "小学生, 中学生, 高校生, 一般, 行政機関等",
    summary: "遠征中の長距離部門部員が陸上教室を実施。ストレッチや動きづくり、リレー対決を通じて市民と交流しました。",
    url: "https://www.instagram.com/p/DGXA1RhPf9L/",
    sdgs: "4, 11"
  },
  {
    id: 184,
    facultyName: "",
    department: "TOYOスポーツセンター",
    title: "【硬式野球部】東洋大学・中野区連携事業「少年少女野球教室」",
    role: "企画, 運営参加・支援, 実演, その他",
    type: "セミナー・ワークショップ",
    organizer: "東洋大学、中野区",
    eventName: "少年少女野球教室",
    date: "11/24",
    location: "中野区立哲学堂公園野球場",
    target: "小学生, 行政機関",
    summary: "中野区との連携事業。硬式野球部員14名が、区内在住・在学の小学5・6年生約100名に対し、軟式ボールを使った実技指導を実施。一流選手との交流を通じて、技術向上と心身の成長を支援しました。",
    url: "https://www.toyo.ac.jp/news/20241125-16389.html",
    sdgs: "4, 11, 16, 17"
  },
  {
    id: 185,
    facultyName: "",
    department: "TOYOスポーツセンター",
    title: "【水泳部】福島市で水泳教室を開催",
    role: "講師, 助言・指導, 企画, 運営参加・支援, 実演",
    type: "セミナー・ワークショップ",
    organizer: "水泳部",
    eventName: "福島市水泳教室",
    date: "8/25",
    location: "福島市中央市民プール",
    target: "小学生, 中学生, 高校生",
    summary: "福島市内の子どもたちを対象に開催。パリ五輪出場の松下選手や竹原選手、平井コーチも参加。レベル別の指導やサイン会を通じて交流しました。",
    url: "https://www.sportspc.jp/?p=8980",
    sdgs: "4, 11"
  }
];