import { Activity } from './types';

export const KENKYU_HUMAN_DATA: Activity[] = [
  {
    id: 33,
    facultyName: "",
    department: "研究推進課",
    title: "SDGsと人文学　公開セミナー",
    role: "講師",
    type: "セミナー・ワークショップ",
    organizer: "人間科学総合研究所",
    eventName: "SDGsと人文学　公開セミナー",
    date: "6/22-1/25",
    location: "東洋大学白山キャンパス",
    target: "高校生, 大学生, 大学院生, 社会人・一般",
    summary: "SDGsの達成に人間科学総合研究所として貢献することをめざし、若手研究者たちがSDGsの問題群を考察する公開セミナーを開催。開催後は講演録を発行・公開している。",
    url: "https://sites.google.com/toyo.jp/ihs/news/20240622SDGs",
    sdgs: "4, 5, 8, 10, 16"
  },
  {
    id: 34,
    facultyName: "",
    department: "研究推進課",
    title: "発達臨床相談室活動",
    role: "講師, 助言・指導",
    type: "講演会",
    organizer: "人間科学総合研究所",
    eventName: "文京区教育委員会リーダー会議「こどもの権利を条例に活かす」ほか",
    date: "1/24-3/24",
    location: "文京区民センターほか",
    target: "社会人・一般, 行政機関",
    summary: "人間の生涯発達に関する諸問題について総合的な研究を行うとともに、地域自治体と連携したこどもの権利に関する研修等を実施。",
    url: "",
    sdgs: "3"
  },
  {
    id: 35,
    facultyName: "",
    department: "研究推進課",
    title: "地域での支援力を生かす子ども相談支援の開発支援",
    role: "出演, 講師, 企画",
    type: "セミナー・ワークショップ",
    organizer: "人間科学総合研究所ほか",
    eventName: "アザラシ型セラピーロボットパロ交流体験セミナーほか",
    date: "6/20-12/14",
    location: "東洋大学ほか",
    target: "幼稚園以下, 小学生, 大学生, 社会人・一般",
    summary: "心身の障害や疾病をもつ子ども、被災地の子どもなど、相談機関に出向くことが難しい地域での相談支援やロボット・アニマルセラピー体験を実施。",
    url: "https://sites.google.com/toyo.jp/ihs/news/20240620s",
    sdgs: "3"
  },
  {
    id: 36,
    facultyName: "",
    department: "研究推進課",
    title: "若手研究チーム「子どもの権利条約の具体化に関する研究」",
    role: "コメンテーター, 企画",
    type: "講演会",
    organizer: "人間科学総合研究所",
    eventName: "子どもの権利条約の具体化に関する研究会",
    date: "通年",
    location: "学内",
    target: "大学院生, 教育関係者, 研究者, 社会人・一般",
    summary: "子どもの権利条約の具体化とその課題を検討する公開研究会を実施し、子ども虐待対応等の現場の関心を研究につなげる社会啓発活動。",
    url: "",
    sdgs: "3"
  },
  {
    id: 37,
    facultyName: "",
    department: "研究推進課",
    title: "「家族・カップル・個人の日仏比較研究」公開講演会",
    role: "講師, 企画",
    type: "講演会",
    organizer: "人間科学総合研究所",
    eventName: "「家族・カップル・個人の日仏比較研究」公開講演会ほか",
    date: "2023/7/8-2025/2/2",
    location: "白山キャンパス・オンラインほか",
    target: "大学生, 教育関係者, 研究者",
    summary: "日仏比較から見る個人のゆくえ、世代関係、10代親の子育て支援モデルなど、家族と個人に関する国際的な研究成果を社会に発信。",
    url: "https://www.toyo.ac.jp/news/research_labo-center_ihs_20230708.html",
    sdgs: "3"
  },
  {
    id: 38,
    facultyName: "",
    department: "研究推進課",
    title: "竹内チーム公開講演会「アジアにおける人的交流の歴史的諸相」",
    role: "講師, 企画",
    type: "講演会",
    organizer: "人間科学総合研究所",
    eventName: "移動する人の帰属―6世紀前半の東アジア",
    date: "1/12",
    location: "白山キャンパス・オンライン",
    target: "研究者, 一般",
    summary: "東アジアの歴史的な人的交流と帰属の問題について、最新の研究成果を公開。",
    url: "https://sites.google.com/toyo.jp/ihs/news/20250112",
    sdgs: "3"
  },
  {
    id: 39,
    facultyName: "",
    department: "研究推進課",
    title: "UEHIRO人科研支援プログラム 公開講演会",
    role: "講師, 企画",
    type: "講演会",
    organizer: "人間科学総合研究所",
    eventName: "「挙国一致」の誕生―明治・大正期の政治体制構想と言説",
    date: "2/15",
    location: "白山キャンパス・オンライン",
    target: "研究者, 一般",
    summary: "上廣倫理財団の支援による若手研究者育成プログラムの一環として、近代日本の政治体制に関する研究成果を公開。",
    url: "https://sites.google.com/toyo.jp/ihs/news/2025215",
    sdgs: "3"
  },
  {
    id: 40,
    facultyName: "",
    department: "研究推進課",
    title: "平島チーム公開研究会「ヒトの移動と多文化社会」",
    role: "講師, 企画",
    type: "講演会",
    organizer: "人間科学総合研究所",
    eventName: "アチェ人によるインドネシア華人文化の保存運動",
    date: "1/15",
    location: "白山キャンパス・オンライン",
    target: "研究者, 一般",
    summary: "インドネシアにおける多文化社会と文化保存の動きについての研究成果を公開。",
    url: "https://sites.google.com/toyo.jp/ihs/news/ihs20250125b",
    sdgs: "3"
  },
  {
    id: 41,
    facultyName: "",
    department: "研究推進課",
    title: "十重田チーム公開研究会「異世界へのまなざし」",
    role: "講師, 企画",
    type: "講演会",
    organizer: "人間科学総合研究所",
    eventName: "生活様式、偶発性と「他者」－思想史と現代を結ぶ",
    date: "2/7",
    location: "オンライン",
    target: "研究者, 一般",
    summary: "思想史の観点から現代における「他者」の問題を考察する公開研究会を開催。",
    url: "https://sites.google.com/toyo.jp/ihs/news/0207",
    sdgs: "3"
  },
  {
    id: 42,
    facultyName: "",
    department: "研究推進課",
    title: "死のこちら側と死の向こう側 ― 近世から現代へ",
    role: "講師, 企画",
    type: "講演会",
    organizer: "人間科学総合研究所",
    eventName: "函館五稜郭の「郷土」史家 片上楽天の“終活”ほか",
    date: "2024/12/14-2025/2/24",
    location: "白山キャンパス・オンライン",
    target: "研究者, 一般",
    summary: "死生観の変遷や歴史的人物、郷土史家の活動を通じ、「死」を巡る歴史と現代的課題を考察。",
    url: "https://sites.google.com/toyo.jp/ihs/news/20241214",
    sdgs: ""
  }
];
