import { Activity } from './types';

export const ARCHITECTURE_DATA: Activity[] = [
  {
    id: 53,
    facultyName: "伊藤 暁",
    department: "理工学部 建築学科",
    title: "日本建築学会建築雑誌編集委員",
    role: "取材協力, インタビュアー, 編集, 企画",
    type: "会誌・広報誌",
    organizer: "日本建築学会",
    eventName: "建築雑誌",
    date: "2024〜2025",
    location: "―",
    target: "学術団体",
    summary: "日本建築学会会誌「建築雑誌」の編集委員を務めた。",
    url: "http://jabs.aij.or.jp/committee/",
    sdgs: "18"
  },
  {
    id: 54,
    facultyName: "伊藤 暁",
    department: "理工学部 建築学科",
    title: "保土ヶ谷の住宅",
    role: "その他",
    type: "新聞・雑誌",
    organizer: "新建築社",
    eventName: "新建築住宅特集 2025年2月号",
    date: "2025/2",
    location: "126-131頁",
    target: "大学生, 大学院生, 研究者, 社会人・一般, 学術団体, 企業, メディア",
    summary: "建築専門誌「新建築住宅特集」にて「保土ヶ谷の住宅」を発表。",
    url: "https://japan-architect.co.jp/shop/jutakutokushu/jt-202502/",
    sdgs: "11, 12"
  },
  {
    id: 55,
    facultyName: "伊藤 暁",
    department: "理工学部 建築学科",
    title: "えんがわオフィス",
    role: "取材協力, 情報提供",
    type: "その他",
    organizer: "学芸出版社",
    eventName: "空き家大全",
    date: "11/1",
    location: "168-169頁",
    target: "大学生, 大学院生, 研究者, 社会人・一般, 学術団体, 企業, 行政機関, メディア",
    summary: "書籍「建築・まちづくりのための空き家大全」に「えんがわオフィス」が掲載された。取材対応、資料提供などを行なった。",
    url: "https://book.gakugei-pub.co.jp/gakugei-book/9784761529116/",
    sdgs: "11, 12"
  },
  {
    id: 56,
    facultyName: "伊藤 暁",
    department: "理工学部 建築学科",
    title: "武蔵境の住宅",
    role: "取材協力, 情報提供",
    type: "その他",
    organizer: "彰国社",
    eventName: "座りたくなる住宅",
    date: "10/10",
    location: "54-55頁",
    target: "大学生, 大学院生, 研究者, 社会人・一般, 学術団体, 企業, メディア",
    summary: "書籍「座りたくなる住宅」に「武蔵境の住宅」が掲載された。取材対応、資料作成、情報提供などを行なった。",
    url: "https://www.shokokusha.co.jp/?p=16860/",
    sdgs: "11, 12"
  },
  {
    id: 57,
    facultyName: "伊藤 暁",
    department: "理工学部 建築学科",
    title: "玩具と住宅",
    role: "インタビュアー, 編集, 企画, 報告書執筆",
    type: "会誌・広報誌",
    organizer: "日本建築士会連合会",
    eventName: "建築士 2025年1月号",
    date: "12/1",
    location: "6-9頁、12-33頁",
    target: "教育関係者, 研究者, 社会人・一般, 学術団体, 企業, 行政機関, メディア",
    summary: "日本建築士会連合会の会誌「建築士」において、2025年1月号の特集記事「玩具と住宅」の企画及び編集・執筆を行なった。",
    url: "https://www.kenchikushikai.or.jp/torikumi/kaishi/index.html",
    sdgs: "11, 12"
  },
  {
    id: 58,
    facultyName: "伊藤 暁",
    department: "理工学部 建築学科",
    title: "戸塚の社屋",
    role: "その他",
    type: "新聞・雑誌",
    organizer: "建築資料研究社",
    eventName: "コンフォルト 2024年4月号",
    date: "4/1",
    location: "25-31頁",
    target: "大学生, 大学院生, 研究者, 社会人・一般, 学術団体, 企業, メディア",
    summary: "雑誌「コンフォルト」No.196、2024年4月号にて「戸塚の社屋」を発表。",
    url: "https://confortmag.net/no-196/",
    sdgs: "11, 12"
  },
  {
    id: 59,
    facultyName: "伊藤 暁",
    department: "理工学部 建築学科",
    title: "無名の小屋",
    role: "寄稿",
    type: "新聞・雑誌",
    organizer: "新建築社",
    eventName: "新建築住宅特集 2025年4月号",
    date: "3/1",
    location: "13頁",
    target: "大学生, 大学院生, 研究者, 社会人・一般, 学術団体, 企業, メディア",
    summary: "建築専門誌「新建築住宅特集」の特集記事「小屋を語る」に、論考「無名の小屋」を寄稿。",
    url: "https://japan-architect.co.jp/shop/jutakutokushu/jt-202504/",
    sdgs: "11, 12"
  },
  {
    id: 60,
    facultyName: "伊藤 暁",
    department: "理工学部 建築学科",
    title: "観察と設計と納まり",
    role: "出演, パネリスト",
    type: "講演会",
    organizer: "納まり放浪記徳島編実行委員会/木村松本建築設計事務所",
    eventName: "納まり放浪記徳島編",
    date: "4/5",
    location: "アクアチッタ第二倉庫",
    target: "高校生, 大学生, 大学院生, 教育関係者, 研究者, 社会人・一般, 学術団体, 企業, 市民団体, 行政機関, メディア",
    summary: "トークイベント「納まり放浪記徳島編」にパネリストとして出演。",
    url: "https://book.gakugei-pub.co.jp/event-24751884d6/",
    sdgs: "11, 12"
  },
  {
    id: 61,
    facultyName: "伊藤 暁",
    department: "理工学部 建築学科",
    title: "建築と音楽の話をしよう",
    role: "出演, パネリスト",
    type: "取材協力",
    organizer: "出雲路本製作所",
    eventName: "建築と音楽の話をしよう",
    date: "4/24",
    location: "誠光社",
    target: "高校生, 大学生, 大学院生, 教育関係者, 保護者, 研究者, 社会人・一般, 学術団体, 企業, 市民団体, メディア",
    summary: "トークイベント「建築と音楽の話をしよう」にパネリストとして出演。",
    url: "https://www.seikosha-books.com/event/9749",
    sdgs: "11, 12"
  },
  {
    id: 62,
    facultyName: "伊藤 暁",
    department: "理工学部 建築学科",
    title: "建築と植物からみえる、あたらしい世界",
    role: "出演, パネリスト",
    type: "取材協力",
    organizer: "出雲路本製作所",
    eventName: "建築と植物からみえる、あたらしい世界",
    date: "5/29",
    location: "ユニテ",
    target: "高校生, 大学生, 大学院生, 教育関係者, 保護者, 研究者, 社会人・一般, 学術団体, 企業, 市民団体, メディア",
    summary: "トークイベント「建築と植物からみえる、あたらしい世界」にパネリストとして出演。",
    url: "https://x.com/unite_books/status/1795019502192635906",
    sdgs: "11, 12"
  },
  {
    id: 63,
    facultyName: "伊藤 暁",
    department: "理工学部 建築学科",
    title: "菊川で街を勝手に面白がる日",
    role: "出演, パネリスト",
    type: "取材協力",
    organizer: "綴る",
    eventName: "菊川で街を勝手に面白がる日",
    date: "12/22",
    location: "イクヤマ家",
    target: "高校生, 大学生, 大学院生, 教育関係者, 保護者, 研究者, 社会人・一般, 学術団体, 企業, 市民団体, メディア",
    summary: "トークイベント「菊川で街を勝手に面白がる日」にパネリストとして出演。",
    url: "https://peatix.com/event/4212549",
    sdgs: "11, 12"
  },
  {
    id: 64,
    facultyName: "篠崎 正彦",
    department: "理工学部 建築学科",
    title: "さいたま市市民活動推進委員会",
    role: "司会, 運営参加・支援",
    type: "その他",
    organizer: "さいたま市",
    eventName: "―",
    date: "通年で計7回",
    location: "さいたま市コムナーレ",
    target: "市民団体",
    summary: "さいたま市長の答申を受けて、市内の市民活動を促進、支援する方策について議論を行うほか、市民活動団体への補助金の審査を行なった。",
    url: "https://www.city.saitama.lg.jp/001/013/003/002/003/001/015/p003098.html",
    sdgs: "3, 4, 5, 7, 8, 11, 17"
  },
  {
    id: 65,
    facultyName: "篠崎 正彦",
    department: "理工学部 建築学科",
    title: "広域飯能斎場最美事業プロポーザル選定委員会",
    role: "司会, 助言・指導, 運営参加・支援",
    type: "その他",
    organizer: "広域飯能斎場",
    eventName: "設計/火葬炉プロポーザル選定",
    date: "通年で計4回/2回",
    location: "飯能市役所など",
    target: "行政機関",
    summary: "広域飯能斎場の建替えに伴う建築と火葬路のプロポーザル審査と事業者選定後の設計案についての助言。",
    url: "http://www.kouikihanno.jp/",
    sdgs: "3, 7, 11"
  }
];
