import { Activity } from './types';

export const KENKYU_BIO_DATA: Activity[] = [
  {
    id: 109,
    facultyName: "",
    department: "研究推進課",
    title: "スマホ顕微鏡でクマムシを見よう",
    role: "講師",
    type: "セミナー・ワークショップ",
    organizer: "神奈川県立産業技術総合研究所（管轄：バイオレジリエンス研究プロジェクト（BRRP））",
    eventName: "KISTEC理科実験室",
    date: "6/8",
    location: "かながわサイエンスパーク",
    target: "小学生",
    summary: "身近な苔の中に潜むクマムシをスマホ顕微鏡で観察。子供たちの理科への意識変容を調査するアウトリーチ活動。伊藤プロジェクトリーダーが講師として参加。",
    url: "https://toyobioresilience.jp/blog/2024-06-08.html",
    sdgs: "4"
  },
  {
    id: 110,
    facultyName: "",
    department: "研究推進課",
    title: "バイオレジリエンス研究プロジェクト 第2期キックオフシンポジウム",
    role: "出演, 講師, 運営",
    type: "講演会",
    organizer: "バイオレジリエンス研究プロジェクト（BRRP）",
    eventName: "極限環境微生物で循環型社会を実現し、生活環境を豊かに！",
    date: "6/22",
    location: "東洋大学朝霞キャンパス",
    target: "大学生, 教育関係者, 研究者, 社会人・一般",
    summary: "朝霞キャンパス移転後の新環境にて、福士東京大教授らを招いた基調講演や成果報告を実施。第2期プロジェクトの方向性を広く発信。",
    url: "https://toyobioresilience.jp/blog/2024-07-08.html",
    sdgs: "4, 9"
  },
  {
    id: 111,
    facultyName: "",
    department: "研究推進課",
    title: "国際発酵・醸造食品産業展 講演",
    role: "講師",
    type: "講演会",
    organizer: "TSO International（管轄：バイオレジリエンス研究プロジェクト（BRRP））",
    eventName: "キャンパス内酵母による日本酒開発成果発表",
    date: "7/30-8/1",
    location: "東京ビッグサイト",
    target: "企業, 研究者, 一般",
    summary: "学内に自生する花から分離した酵母で醸造した日本酒「越生梅林エスティ」について、開発秘話と地域ブランド化の取り組みを講演。峯岸先生が登壇。",
    url: "https://toyobioresilience.jp/blog/2024-07-302.html",
    sdgs: "9"
  },
  {
    id: 112,
    facultyName: "",
    department: "研究推進課",
    title: "かわさきサイエンスチャレンジでの理科実験",
    role: "講師",
    type: "セミナー・ワークショップ",
    organizer: "かわさきサイエンスチャレンジ運営委員会（管轄：バイオレジリエンス研究プロジェクト（BRRP））",
    eventName: "100倍の日常をスマホで楽しむクマムシ観察会",
    date: "8/3",
    location: "かながわサイエンスパーク（KSP）",
    target: "小学生",
    summary: "70名を超える小学生に対し、極限環境微生物の先端研究成果を分かりやすく紹介。将来の科学者を育てる教育コンテンツを提供。伊藤プロジェクトリーダーが担当。",
    url: "https://toyobioresilience.jp/blog/2024-08-03.html",
    sdgs: "4"
  },
  {
    id: 113,
    facultyName: "",
    department: "研究推進課",
    title: "BRRPセミナー 第1回〜第2回",
    role: "講師, 企画, 運営",
    type: "講演会",
    organizer: "バイオレジリエンス研究プロジェクト（BRRP）",
    eventName: "高機能生体触媒の開発・リボソームの進化工学",
    date: "10/17, 11/14",
    location: "東洋大学朝霞キャンパス",
    target: "大学生, 研究者, 一般",
    summary: "大阪公立大や大阪大の専門家を招き、最先端の細胞進化工学や生体触媒に関する知見を共有。活発な質疑応答で学生に刺激を提供。",
    url: "https://toyobioresilience.jp/blog/2024-10-18.html",
    sdgs: "4"
  },
  {
    id: 114,
    facultyName: "",
    department: "研究推進課",
    title: "アグリビジネス創出フェア2024出展",
    role: "情報提供, 運営支援",
    type: "セミナー・ワークショップ",
    organizer: "農林水産省（管轄：バイオレジリエンス研究プロジェクト（BRRP））",
    eventName: "アグリビジネス創出フェア2024",
    date: "11/26",
    location: "東京ビッグサイト",
    target: "企業, 行政機関, 一般",
    summary: "峯岸研究室・伊藤研究室・高品研究室の成果をポスター展示。多くの来場企業と新たな共同研究の可能性について具体的な意見交換を実施。",
    url: "https://toyobioresilience.jp/blog/2024-11-28.html",
    sdgs: "9"
  },
  {
    id: 115,
    facultyName: "",
    department: "研究推進課",
    title: "2024年度 バイオレジリエンス研究プロジェクト成果報告会",
    role: "出演, 講師, 企画",
    type: "講演会",
    organizer: "バイオレジリエンス研究プロジェクト（BRRP）",
    eventName: "極限環境微生物で循環型社会を実現し、生活環境を豊かに！",
    date: "2/26",
    location: "朝霞キャンパス・オンライン",
    target: "大学生, 研究者, 社会人・一般",
    summary: "東洋大学重点研究推進プログラムの集大成として、研究成果のポスター発表やシンポジウムを通じ、社会実装への展望を報告。",
    url: "https://toyobioresilience.jp/blog/2025-01-09.html",
    sdgs: "9"
  }
];