import { Activity } from './types';

export const KENKYU_MODERN_DATA: Activity[] = [
  {
    id: 43,
    facultyName: "",
    department: "研究推進課",
    title: "SDGｓプロジェクト",
    role: "調査担当, 報告書執筆",
    type: "調査",
    organizer: "現代社会総合研究所",
    eventName: "地域再生学に関する調査アンケートほか",
    date: "継続中",
    location: "全国・Web",
    target: "行政機関, 研究者, 一般",
    summary: "全国1557自治体を対象とした地域創生アンケートや、富山県魚津市との産官学連携、ドローンを活用した農業支援などを推進。",
    url: "https://sites.google.com/toyo.jp/gensha/project/projectSDGs/20250103",
    sdgs: "3, 8, 11, 12, 13, 14, 15"
  },
  {
    id: 44,
    facultyName: "",
    department: "研究推進課",
    title: "IR チーム・地方創生プロジェクト",
    role: "調査, 企画",
    type: "調査",
    organizer: "現代社会総合研究所",
    eventName: "大阪市IR推進局・韓国ソウル市役所への現地視察",
    date: "6月, 9月",
    location: "大阪市夢洲, 韓国ソウル市",
    target: "行政機関, 大学生",
    summary: "統合型リゾート（IR）が地域創生に与える影響や依存症等の社会的課題について、国内外の自治体を訪問し意見交換と視察を実施。",
    url: "",
    sdgs: "8, 9, 11"
  },
  {
    id: 45,
    facultyName: "",
    department: "研究推進課",
    title: "ICT 教育研究プロジェクト",
    role: "企画, 調査",
    type: "調査",
    organizer: "現代社会総合研究所",
    eventName: "佐賀県武雄市役所へのICT教育現状調査",
    date: "12月",
    location: "佐賀県武雄市",
    target: "教育関係者, 行政機関",
    summary: "AIの積極導入を図る自治体への調査を通じ、ICT教育の格差是正や学習効果の向上策を研究。",
    url: "https://sites.google.com/toyo.jp/gensha/project/ICTproject",
    sdgs: "4"
  },
  {
    id: 46,
    facultyName: "",
    department: "研究推進課",
    title: "公開シンポジウム「卒業生に聞く!シリーズ1」",
    role: "司会, 企画",
    type: "講演会",
    organizer: "現代社会総合研究所",
    eventName: "「卒業生に聞く」シリーズ①：コンテンツツーリズムと地域振興",
    date: "5/18",
    location: "東洋大学125記念ホール",
    target: "大学生, 一般",
    summary: "アニメや声優を活用した地域振興プロジェクト(PROJECT758)を例に、物語性による観光資源化を解説。",
    url: "https://sites.google.com/toyo.jp/gensha/lecture2/20240518",
    sdgs: "4"
  },
  {
    id: 47,
    facultyName: "",
    department: "研究推進課",
    title: "楽天グループにおけるDEIとSustainabilityへの取り組み",
    role: "パネリスト, 企画",
    type: "講演会",
    organizer: "現代社会総合研究所",
    eventName: "公開講演会",
    date: "5/20",
    location: "東洋大学スカイホール",
    target: "大学生, 研究者, 企業",
    summary: "企業の多様性（DEI）と持続可能性への具体的な取り組みを、楽天グループのマネージャーを招いて紹介。",
    url: "https://sites.google.com/toyo.jp/gensha/lecture2/20240520",
    sdgs: "4, 9"
  },
  {
    id: 48,
    facultyName: "",
    department: "研究推進課",
    title: "起業家に聞く（シリーズ②）「ドローン×ビジネス」",
    role: "パネリスト, 司会",
    type: "講演会",
    organizer: "現代社会総合研究所",
    eventName: "公開講演会",
    date: "6/22",
    location: "東洋大学125記念ホール",
    target: "大学生, 研究者",
    summary: "ドローン技術を活用した新しいビジネスモデルの可能性について、現役の起業家を招いて議論。",
    url: "https://sites.google.com/toyo.jp/gensha/lecture2/20240622",
    sdgs: "4, 9"
  },
  {
    id: 49,
    facultyName: "",
    department: "研究推進課",
    title: "SDGsとまちづくり／パートナーシップ",
    role: "企画, 調査担当",
    type: "調査",
    organizer: "現代社会総合研究所",
    eventName: "京都市立開建高校インタビュー・栃木県上都賀地区ヒアリングほか",
    date: "継続中",
    location: "京都、栃木、学内",
    target: "高校生, 大学生, 企業",
    summary: "新設校の教育理念調査や、栃木県での農業女子プロジェクト、高校生向けキャリアWSなど、多角的なパートナーシップ研究を推進。",
    url: "",
    sdgs: "8, 9, 11, 12, 17"
  }
];
