import { Activity } from './types';

export const KENKYU_INTL_COEXISTENCE_DATA: Activity[] = [
  {
    id: 89,
    facultyName: "",
    department: "研究推進課",
    title: "Buy One Give One 事業による人道支援研究",
    role: "調査担当, 報告書執筆",
    type: "調査",
    organizer: "国際共生社会研究センター",
    eventName: "ソーラー充電式ランタンの無料配布調査",
    date: "通年",
    location: "ベトナム、パキスタン、タイ国境",
    target: "無電化地域の住民",
    summary: "ミャンマー難民やパキスタンのスラム住民へのソーラーランタン支援を通じ、支援側と受益側の双方にもたらす循環的インパクトを長期検証。",
    url: "https://sites.google.com/toyo.jp/orc/project/bogo",
    sdgs: "1, 7, 10, 12"
  },
  {
    id: 90,
    facultyName: "",
    department: "研究推進課",
    title: "ミャンマー政変の人的資本育成への影響調査",
    role: "調査担当",
    type: "調査",
    organizer: "国際共生社会研究センター",
    eventName: "高等教育と職業訓練に焦点を当てて",
    date: "通年",
    location: "ミャンマー",
    target: "現地の学生",
    summary: "クーデターにより麻痺した教育機関の現状と、学生が被った教育・就業機会の減少を調査。必要とされる支援ニーズを明らかにする。",
    url: "https://sites.google.com/toyo.jp/orc/project/ミャンマー政変",
    sdgs: "4, 16"
  },
  {
    id: 91,
    facultyName: "",
    department: "研究推進課",
    title: "中山間地域の地域資源を活用した地域活性化",
    role: "調査担当, 報告書執筆",
    type: "調査",
    organizer: "国際共生社会研究センター",
    eventName: "小鹿野町「バス待ちマップ」作成・イタリア震災復興提言ほか",
    date: "通年",
    location: "埼玉県小鹿野町、イタリア、ベトナム",
    target: "地域住民, 高校生",
    summary: "国内外の中山間地域を対象に、観光資源の活掘や震災復興の実践的提言を実施。信頼関係をベースとした継続的な学生研修を推進。",
    url: "https://sites.google.com/toyo.jp/orc/project/中山間地域",
    sdgs: "1, 9, 11"
  },
  {
    id: 92,
    facultyName: "",
    department: "研究推進課",
    title: "トルコ・シリア地震後の復興都市計画共同研究",
    role: "調査担当, 報告書執筆",
    type: "調査",
    organizer: "国際共生社会研究センター",
    eventName: "がれき処理と持続的な街づくり支援",
    date: "通年",
    location: "トルコ東部",
    target: "社会人・一般, 行政機関",
    summary: "甚大な被害を被った東アナトリア地方の復興計画に対し、学術的側面から支援。SMARTなインフラ再建と持続的な街づくりを後押し。",
    url: "https://sites.google.com/toyo.jp/orc/project/トルコシリア地震",
    sdgs: "1, 11, 13, 17"
  },
  {
    id: 93,
    facultyName: "",
    department: "研究推進課",
    title: "MeW（Menstrual Wellbeing）プロジェクトの展開",
    role: "調査担当",
    type: "調査",
    organizer: "国際共生社会研究センター",
    eventName: "白山キャンパス内生理用品無償配布の実証実験",
    date: "通年",
    location: "東洋大学白山キャンパス",
    target: "大学生, 教育関係者",
    summary: "月経のある人のウェルビーイング向上を目的に実証実験を実施。この成果により2024年4月から白山キャンパス全域で大学事業としての配布が開始。",
    url: "https://sites.google.com/toyo.jp/orc/project/mew",
    sdgs: "1, 4, 5, 6, 10, 12"
  },
  {
    id: 94,
    facultyName: "",
    department: "研究推進課",
    title: "コペアレンティングの認識形成国際比較（CopaGloba）",
    role: "調査担当",
    type: "調査",
    organizer: "国際共生社会研究センター（フィンランドアカデミー助成）",
    eventName: "日本・フィンランド・ポルトガルの縦断的比較",
    date: "通年",
    location: "日本、北欧、南欧",
    target: "保護者, 教育関係者",
    summary: "第一子を迎えるカップルへの産前・産後調査を通じ、子育て支援政策へのエビデンスを収集。国際シンポジウム等で知見を発信。",
    url: "―",
    sdgs: "3, 4"
  },
  {
    id: 95,
    facultyName: "",
    department: "研究推進課",
    title: "開発途上国における都市計画・交通のSURFイニシアティブ",
    role: "調査担当, 報告書執筆",
    type: "調査",
    organizer: "国際共生社会研究センター",
    eventName: "スマートシティ型都市開発・マネジメント統合プラットフォームの提示",
    date: "通年",
    location: "学内, 海外",
    target: "一般, 行政機関",
    summary: "無秩序な都市化が進む開発途上国を対象に、デジタル技術やデータ分析に基づく新たな都市管理手法「SURF」を提示し社会実装を目指す。",
    url: "―",
    sdgs: "1, 9, 11, 13"
  },
  {
    id: 96,
    facultyName: "",
    department: "研究推進課",
    title: "紛争国における破壊建造物のリサイクルと都市復興",
    role: "調査担当, 報告書執筆",
    type: "調査",
    organizer: "国際共生社会研究センター",
    eventName: "スーダン・南スーダンにおける道路整備手法構築",
    date: "通年",
    location: "スーダン、南スーダン",
    target: "行政機関",
    summary: "紛争により破壊された建築物を道路整備資材として再利用する手法を構築。復興プロセスの迅速化を図る汎用性のあるモデルを開発。",
    url: "https://kaken.nii.ac.jp/ja/grant/KAKENHI-PROJECT-24K07736/",
    sdgs: "11, 16"
  },
  {
    id: 97,
    facultyName: "",
    department: "研究推進課",
    title: "CeSDeS Open Seminar On SDGs",
    role: "パネリスト, 講師, 企画",
    type: "セミナー・ワークショップ",
    organizer: "国際共生社会研究センター",
    eventName: "第1回〜第4回オープンセミナー（ロヒンギャ教育・都市管理ほか）",
    date: "4/20-12/20",
    location: "白山キャンパス・オンライン",
    target: "一般, 学生, 研究者",
    summary: "月経とサニテーション、グローバルサウスの都市課題、先住民の知恵と気候変動、ロヒンギャ難民支援など、多岐にわたるSDGs課題を議論。",
    url: "―",
    sdgs: "1, 3, 4, 10, 11, 13, 16"
  },
  {
    id: 98,
    facultyName: "",
    department: "研究推進課",
    title: "センター総括シンポジウム",
    role: "出演, 講師, 企画",
    type: "講演会",
    organizer: "国際共生社会研究センター",
    eventName: "レジリエントな社会からウェルビーイングな社会へ",
    date: "1/20",
    location: "白山キャンパススカイホール",
    target: "一般, 学生, 研究者",
    summary: "重点研究プロジェクトの3年間を総括し、ポストSDGsにおける持続的幸福の追求と今後の研究展望を紹介。",
    url: "―",
    sdgs: "1, 3, 4, 5, 6, 7, 10, 11, 12, 16"
  },
  {
    id: 99,
    facultyName: "",
    department: "研究推進課",
    title: "能登半島地震被災地に関する調査",
    role: "調査担当, 報告書執筆",
    type: "調査",
    organizer: "国際共生社会研究センター",
    eventName: "移動ルートの確保状況と被災状況の確認調査",
    date: "6/5-8",
    location: "石川県能登半島",
    target: "一般, 行政機関",
    summary: "支援の量的確保が困難な能登半島北部を現地調査。珠洲・輪島・志賀町などの被災状況と、復旧・災害ボランティア支援の課題を確認。",
    url: "https://drive.google.com/file/d/1Fm-M9kglwBfzgRsSzyVrByQG17AjfcuS/view",
    sdgs: "3, 11, 17"
  },
  {
    id: 100,
    facultyName: "",
    department: "研究推進課",
    title: "人も地域も長生きできる小さな町の挑戦",
    role: "調査担当, 報告書執筆",
    type: "調査",
    organizer: "国際共生社会研究センター",
    eventName: "南イタリア・ポッリカの「再生」調査",
    date: "7月",
    location: "南イタリア",
    target: "一般",
    summary: "条件不利とされる過疎地域における持続可能性を調査。イタリアの小さな町での再生事例を通じ、地域レジリエンスのヒントを収集。",
    url: "https://drive.google.com/file/d/1fyGK2wm5bL29p-ZtEIyqvpwPhSPpgdcq/view",
    sdgs: "8, 11, 17"
  },
  {
    id: 101,
    facultyName: "",
    department: "研究推進課",
    title: "トンガ災害復興・農村開発プロジェクト調査",
    role: "調査担当, 報告書執筆",
    type: "調査",
    organizer: "国際共生社会研究センター・地球市民の会 共同",
    eventName: "海底火山大噴火と津波被害からの復興基礎情報収集",
    date: "7-8月",
    location: "トンガ王国",
    target: "一般, 市民団体, 行政機関",
    summary: "2022年の災害からの復興支援に向け、現地の被災コミュニティ視察や在トンガ大使館訪問を実施し、産官学連携の基盤を構築。",
    url: "https://drive.google.com/file/d/1v0eymcsxN-kNuZHgvYm9kxV0SFu6cQLi/view",
    sdgs: "11, 17"
  },
  {
    id: 102,
    facultyName: "",
    department: "研究推進課",
    title: "東京国際交流館国際シンポジウム",
    role: "講師, 企画, 情報提供",
    type: "講演会",
    organizer: "東洋大学・東京都立大学・JASSO 共催",
    eventName: "フィンランド、ポルトガル、日本の子育てのカタチ",
    date: "9/20",
    location: "東京国際交流館プラザ平成・オンライン",
    target: "一般, 教育関係者, 行政機関",
    summary: "CopaGlobaプロジェクトの成果として、第一子出産前後の夫婦に対する国際比較調査の結果を報告し、多様な子育てのあり方を議論。",
    url: "https://www.tmu.ac.jp/hot_topics/pr/37014.html",
    sdgs: "3, 4"
  },
  {
    id: 103,
    facultyName: "",
    department: "研究推進課",
    title: "インド・ムンバイのダラーヴィ現地調査",
    role: "調査担当, 報告書執筆",
    type: "調査",
    organizer: "国際共生社会研究センター",
    eventName: "居住と生業が一体となった独特な都市空間の分析",
    date: "10月",
    location: "インド・ムンバイ",
    target: "一般, 研究者",
    summary: "世界最大級のインフォーマル市街地にて、リサイクル産業や窯業など生業と都市空間の関係性をアンケートと観察により調査。",
    url: "https://drive.google.com/file/d/1GsZepUaex78Angm8YeqO-D14C_P4vq1B/view",
    sdgs: "11"
  }
];
