import { Activity } from './types';

export const BUSINESS_FINANCE_DATA: Activity[] = [
  {
    id: 15,
    facultyName: "越智 信彰",
    department: "経営学部 会計ファイナンス学科",
    title: "自治体職員向け講演『光害の概要と対策について』",
    role: "講師",
    type: "セミナー・ワークショップ",
    organizer: "日本建築学会 色彩設計小委員会 夜間景観ワーキンググループ",
    eventName: "夜間景観ワークショップ",
    date: "5/10",
    location: "関西大学",
    target: "社会人・一般, 行政機関",
    summary: "兵庫県内自治体の景観担当者7名が対象のワークショップ内での講演。講演30分。",
    url: "https://ris.toyo.ac.jp/profile/ja.f6acabc938306d1869dd55e26e89b248.html#SocialContribution",
    sdgs: "11"
  },
  {
    id: 16,
    facultyName: "越智 信彰",
    department: "経営学部 会計ファイナンス学科",
    title: "環境科学セミナー『光害のない街へ ～光害対策の考え方とダークスカイ活動の紹介～』",
    role: "講師",
    type: "セミナー・ワークショップ",
    organizer: "滋賀県立大学環境科学部",
    eventName: "2024環境科学セミナー",
    date: "7/11",
    location: "滋賀県立大学環境科学部 会議室",
    target: "大学生, 大学院生",
    summary: "建築を学ぶ大学院生・学部生が主な対象。聴講約15名。講演80分。",
    url: "https://ris.toyo.ac.jp/profile/ja.f6acabc938306d1869dd55e26e89b248.html#SocialContribution",
    sdgs: "11"
  },
  {
    id: 17,
    facultyName: "越智 信彰",
    department: "経営学部 会計ファイナンス学科",
    title: "小学生向け出前講座『楽しく学ぶ照明教室』",
    role: "講師",
    type: "出前授業",
    organizer: "照明学会東京支部",
    eventName: "楽しく学ぶ照明教室",
    date: "8/5, 8/20",
    location: "ギャラクシティ（足立区）",
    target: "小学生, 中学生",
    summary: "8/5\n「光の実験と光害について」を担当（50分）。手回し発電機を使った実験、ダークスカイキットの実演などを通し、光の性質や光害について学ぶ。参加16名。 【アンケート結果（回答数16）】 ・話はわかりやすかったですか。 とてもわかった88%、まあまあわかった13%、どちらでもない0%、あまりわからなかった0%、ぜんぜんわからなかった0% ・話の内容に興味を持ちましたか。 興味を持った56%、少し興味を持った31%、どちらでもない6%、少しつまらなかった6%、つまらなかった0%\n8/20\n「光の実験と光害について」を担当（50分）。手回し発電機を使った実験、ダークスカイキットの実演などを通し、光の性質や光害について学ぶ。参加11名。 【アンケート結果（回答数11）】 ・話はわかりやすかったですか。 とてもわかった91%、まあまあわかった9%、どちらでもない0%、あまりわからなかった0%、ぜんぜんわからなかった0% ・話の内容に興味を持ちましたか。 興味を持った91%、少し興味を持った9%、どちらでもない0%、少しつまらなかった0%、つまらなかった0%",
    url: "https://ieij.org/shibu/tokyo/info2024/240805_0820seminar-result.html",
    sdgs: "11"
  },
  {
    id: 18,
    facultyName: "越智 信彰",
    department: "経営学部 会計ファイナンス学科",
    title: "一般向け講演『身近な環境問題「光害」から自然との共生を考える』",
    role: "講師",
    type: "セミナー・ ワークショップ",
    organizer: "東京都中央区",
    eventName: "令和6年度中央区総合環境講座",
    date: "8/21",
    location: "中央区立環境情報センター「エコノバ」",
    target: "社会人・一般",
    summary: "天の川を見たことがありますか？暗いはずの夜に、私たちは大量の人工光を灯し、街には過剰な光が溢れています。この「光害」の問題を通して、地球環境、生態系、人間社会の関わりを考えてみましょう。 （案内チラシより）\n講演90分＋照明見学25分。参加者10名。",
    url: "https://ris.toyo.ac.jp/profile/ja.f6acabc938306d1869dd55e26e89b248.html#SocialContribution",
    sdgs: "11"
  },
  {
    id: 19,
    facultyName: "越智 信彰",
    department: "経営学部 会計ファイナンス学科",
    title: "大学生向け講演『光害の概要とダークスカイ活動の紹介』",
    role: "講師",
    type: "セミナー・ ワークショップ",
    organizer: "(株)ライティングプランナーズアソシエーツ",
    eventName: "面出薫／照明デザイン塾  ３ day Workshop",
    date: "9/21",
    location: "LPAオフィス",
    target: "大学生, 大学院生",
    summary: "「建築、インテリア、ランドスケープ、都市環境等を学ぶ学生にとって照明デザインは大切な学習項目です。しかし日本では本格的に照明デザインを学ぶ機会が殆どありません。３日間に集中した高密度なワークショップです。９月の３連休に照明デザインを集中的に学習してみませんか。」（案内チラシより）\n外部講師として講演50分。全国から参加の大学生・大学院生20名が聴講。",
    url: "https://www.lighting.co.jp/ja/2024/06/24/kaoru-mende-lighting-design-workshop-3-day-workshop/",
    sdgs: "11"
  },
  {
    id: 20,
    facultyName: "越智 信彰",
    department: "経営学部 会計ファイナンス学科",
    title: "「星空保護区シンポジウム in やんばる」を開催",
    role: "講師",
    type: "講演会",
    organizer: "主催：ダークスカイ・ジャパン、国頭村 / 共催：星空保護推進機構 / 協力：星空公団 / 協賛：沖縄JTB株式会社、日本トランスオーシャン航空株式会社、一般財団法人沖縄観光コンベンションビューロー(OCVB)、株式会社I-ne / 後援：環境省沖縄奄美自然環境事務所、沖縄県",
    eventName: "星空保護区シンポジウム in やんばる",
    date: "9/28",
    location: "国頭村民ふれあいセンター",
    target: "社会人・一般",
    summary: "沖縄県国頭村では、今年秋に村内4公園を星空保護区（ダークスカイ・パーク）に申請することを予定しております。星空保護区や光害対策について、より広くご理解いただきたく、国頭村および広く周辺地域のみなさまを対象としたシンポジウムを開催いたします。ぜひお気軽にご参加ください。後日、YouTubeでのアーカイブ配信も予定しております。",
    url: "https://darksky.jp/sympo2024/",
    sdgs: "11"
  },
  {
    id: 21,
    facultyName: "越智 信彰",
    department: "経営学部 会計ファイナンス学科",
    title: "高校新聞部への取材協力",
    role: "取材協力",
    type: "研究指導",
    organizer: "越谷北高校新聞部",
    eventName: "越谷北高新聞第571号",
    date: "10/18",
    location: "越谷北高校",
    target: "高校生",
    summary: "越谷北高校新聞部の取材を受け、2024年12月16日発行の越谷北高新聞第571号にて記事「特集・星とオーロラ 光が生み出す善と悪」の中で光害の解説記事として掲載された。",
    url: "https://ris.toyo.ac.jp/profile/ja.f6acabc938306d1869dd55e26e89b248.html#SocialContribution",
    sdgs: "11"
  },
  {
    id: 22,
    facultyName: "越智 信彰",
    department: "経営学部 会計ファイナンス学科",
    title: "中学校出前授業『南房総の星空を守ろう、誇ろう！～光害のはなし～』",
    role: "講師",
    type: "出前授業",
    organizer: "南房総市立富山中学校",
    eventName: "中学校出前授業『南房総の星空を守ろう、誇ろう！～光害のはなし～』",
    date: "11/8",
    location: "南房総市立富山中学校",
    target: "中学生",
    summary: "出前授業の講師を務めた。富山中学校1～3年生約90名が参加。講演50分。",
    url: "https://www.tokyo-np.co.jp/article/372876",
    sdgs: "11"
  },
  {
    id: 23,
    facultyName: "越智 信彰",
    department: "経営学部 会計ファイナンス学科",
    title: "中学校出前授業『南房総の星空を守ろう、誇ろう！～光害のはなし～』",
    role: "講師",
    type: "出前授業",
    organizer: "南房総市立嶺南中学校",
    eventName: "中学校出前授業『南房総の星空を守ろう、誇ろう！～光害のはなし～』",
    date: "11/8",
    location: "南房総市立嶺南中学校",
    target: "中学生",
    summary: "出前授業の講師を務めた。嶺南中学校１年生約40名が参加。講演50分。",
    url: "https://darksky.jp/2036/",
    sdgs: "11"
  },
  {
    id: 24,
    facultyName: "越智 信彰",
    department: "経営学部 会計ファイナンス学科",
    title: "一般向け講演『星空保護区認定制度について』",
    role: "講師",
    type: "講演会",
    organizer: "開田高原地域協議会",
    eventName: "第14回開田高原大懇談会",
    date: "11/30",
    location: "開田高原末川研修センター",
    target: "社会人・一般",
    summary: "星空保護区と光害対策について解説した。講演約30分。参加者約30名。",
    url: "https://ris.toyo.ac.jp/profile/ja.f6acabc938306d1869dd55e26e89b248.html#SocialContribution",
    sdgs: "11"
  },
  {
    id: 25,
    facultyName: "越智 信彰",
    department: "経営学部 会計ファイナンス学科",
    title: "小学生向け出前講座『楽しく学ぶ照明教室』",
    role: "講師",
    type: "出前授業",
    organizer: "照明学会東京支部",
    eventName: "楽しく学ぶ照明教室",
    date: "12/26",
    location: "江戸川区子ども未来館",
    target: "小学生",
    summary: "「光の実験と光害について」を担当（50分）。手回し発電機を使った実験、ダークスカイキットの実演などを通し、光の性質や光害について学ぶ。参加児童11名、保護者11名。 【アンケート結果（回答数11）】 ・話はわかりやすかったですか。 とてもわかった100%、まあまあわかった0%、どちらでもない0%、あまりわからなかった0%、ぜんぜんわからなかった0% ・話の内容に興味を持ちましたか。 興味を持った73%、少し興味を持った18%、どちらでもない9%、少しつまらなかった0%、つまらなかった0%",
    url: "https://ieij.org/shibu/tokyo/info2024/241226seminar-result.html",
    sdgs: "11"
  },
  {
    id: 26,
    facultyName: "越智 信彰",
    department: "経営学部 会計ファイナンス学科",
    title: "講演『光害の概要と対策について』",
    role: "講師",
    type: "セミナー・ワークショップ",
    organizer: "公益財団法人 日本生態系協会",
    eventName: "公益財団法人日本生態系協会の勉強会",
    date: "3/25",
    location: "－",
    target: "社会人・一般",
    summary: "公益財団法人日本生態系協会の勉強会にて講演。60分。協会の役員・職員約20名が参加。",
    url: "https://ris.toyo.ac.jp/profile/ja.f6acabc938306d1869dd55e26e89b248.html#SocialContribution",
    sdgs: "11"
  },
  {
    id: 27,
    facultyName: "越智 信彰",
    department: "経営学部 会計ファイナンス学科",
    title: "小学生向け出前講座『楽しく学ぶ照明教室』",
    role: "講師",
    type: "出前授業",
    organizer: "照明学会東京支部",
    eventName: "楽しく学ぶ照明教室",
    date: "3/26",
    location: "コニカミノルタ サイエンスドーム（八王子市こども科学館）",
    target: "小学生",
    summary: "標記イベントにて「光の実験と光害について」を担当（50分）。手回し発電機を使った実験、ダークスカイキットの実演などを通し、光の性質や光害について学ぶ。参加児童14名、保護者12名。 【アンケート結果（回答数14）】 ・話はわかりやすかったですか。 とてもわかった86%、まあまあわかった14%、どちらでもない0%、あまりわからなかった0%、ぜんぜんわからなかった0% ・話の内容に興味を持ちましたか。 興味を持った86%、少し興味を持った7%、どちらでもない7%、少しつまらなかった0%、つまらなかった0%",
    url: "https://ieij.org/shibu/tokyo/info2024/250326seminar-result.html",
    sdgs: "11"
  }
];
