import { Activity } from './types';

export const LAW_DATA: Activity[] = [
  {
    id: 28,
    facultyName: "早川 和宏",
    department: "法学部 法律学科",
    title: "公文書管理のあり方",
    role: "講師",
    type: "講演会",
    organizer: "市町村職員中央研修所（市町村アカデミー）",
    eventName: "情報公開と個人情報保護",
    date: "5/28",
    location: "市町村職員中央研修所（市町村アカデミー）",
    target: "行政機関",
    summary: "公文書管理法の内容を中心に、各自治体の条例等を参照しながら、文書管理上の諸課題を講義した。",
    url: "https://www.jamp.gr.jp/wp-content/uploads/2024/01/leaflet23.05.20_2411029.pdf",
    sdgs: "16"
  },
  {
    id: 29,
    facultyName: "早川 和宏",
    department: "法学部 法律学科",
    title: "公文書管理の基本理念 ～法的視点から～",
    role: "講師",
    type: "講演会",
    organizer: "安曇野市",
    eventName: "安曇野市 適正な公文書管理に関する職員研修会",
    date: "8/22-8/23",
    location: "安曇野市",
    target: "行政機関",
    summary: "安曇野市「適正な公文書管理に関する職員研修会」が開催され、「公文書管理の基本理念 ～法的視点から～」と題して講義を行った。",
    url: "https://ris.toyo.ac.jp/profile/ja.b42b1202901538ecf42f53b55fecb5d8.html#SocialContribution",
    sdgs: "16"
  },
  {
    id: 30,
    facultyName: "早川 和宏",
    department: "法学部 法律学科",
    title: "個人情報保護制度をめぐる最近の動向",
    role: "講師",
    type: "講演会",
    organizer: "川口市",
    eventName: "川口市情報公開・個人情報保護研修会",
    date: "2025/2/20",
    location: "川口市",
    target: "行政機関",
    summary: "川口市情報公開・個人情報保護研修会にて、「個人情報保護制度をめぐる最近の動向」と題して講義を行った。",
    url: "https://frontier-omiya.jp/topics/1230",
    sdgs: "16"
  },
  {
    id: 31,
    facultyName: "早川 和宏",
    department: "法学部 法律学科",
    title: "個人情報の保護及び取扱いについて / 特定個人情報の保護及び取扱いについて",
    role: "講師",
    type: "講演会",
    organizer: "参議院事務局",
    eventName: "個人情報保護等に関する研修　第一部、第二部",
    date: "2025/2/20",
    location: "参議院事務局",
    target: "行政機関",
    summary: "参議院事務局で開催された個人情報保護等に関する研修において、第一部「個人情報の保護及び取扱いについて」、第二部「特定個人情報の保護及び取扱いについて」と題する講演を行った。",
    url: "https://frontier-omiya.jp/topics/1232",
    sdgs: "16"
  },
  {
    id: 32,
    facultyName: "早川 和宏",
    department: "法学部 法律学科",
    title: "大学スポーツのガバナンス（２）",
    role: "パネリスト, 講師",
    type: "講演会",
    organizer: "成城大学体育部連合会OB・OG会",
    eventName: "第6回スポーツ成城FORUM",
    date: "2025/2/22",
    location: "成城大学3号館003教室",
    target: "社会人・一般",
    summary: "成城大学体育部連合会OB・OG会（スポーツ成城）が主催する「第6回　スポーツ成城FORUM講演会」にて、「大学スポーツのガバナンス（２）」と題する講演を行うとともに、パネルディスカッションでパネリストを務めた。",
    url: "https://www.seijo-dosokai.com/archives/16144/",
    sdgs: "16"
  },
  {
    id: 33,
    facultyName: "早川 和宏",
    department: "法学部 法律学科",
    title: "アーカイブズ法制論",
    role: "講師",
    type: "講演会",
    organizer: "主催：大学共同利用機関法人人間文化研究機構 国文学研究資料館",
    eventName: "2024 年度アーカイブズ・カレッジ（史料管理学研修会通算第70回）長期コース後期",
    date: "8/30",
    location: "―",
    target: "大学院生, 研究者, 社会人・一般, 学術団体, 企業, 行政機関",
    summary: "アーカイブズ・カレッジ（史料管理学研修会通算第70回）長期コース後期の「〔科目５〕アーカイブズ管理研究Ⅲ　組織管理と社会貢献」において、「アーカイブズ法制論」と題し、アーカイブズ関連機関が依拠する法律（公文書館法・公文書管理法など）およびアーカイブズの管理・公開に関わる法律（情報公開法・個人情報保護法・著作権法など）の成立事情とその内容を理解し、適切な法解釈能力を身につけるための講義を行った。",
    url: "https://www.nijl.ac.jp/event/img/5c5c34f6cad709f7721b28895d484a60e1463d17.pdf",
    sdgs: "16"
  },
  {
    id: 34,
    facultyName: "早川 和宏",
    department: "法学部 法律学科",
    title: "朝霞市無料法律相談会",
    role: "助言・指導",
    type: "その他",
    organizer: "東洋大学無料法律相談部",
    eventName: "朝霞市無料法律相談会",
    date: "10/5",
    location: "朝霞市 産業文化センター",
    target: "社会人・一般",
    summary: "朝霞市無料法律相談会にて本学の無料法律相談部の顧問として、相談対応に当たった。",
    url: "https://sites.google.com/toyo.jp/law/news_f/20241005",
    sdgs: "16"
  },
  {
    id: 35,
    facultyName: "早川 和宏",
    department: "法学部 法律学科",
    title: "常総市　チャレンジド・フェス",
    role: "運営参加・支援",
    type: "フェスティバル",
    organizer: "常総市",
    eventName: "チャレンジド・フェス／Challenged Festival 2024 in JOSO city",
    date: "12/7",
    location: "常総市 生涯学習センター",
    target: "社会人・一般",
    summary: "常総市にて障がい者の理解促進事業として開催されたチャレンジド・フェスにて、法学部ゼミ生と共にボランティアとしてイベント運営に参加した。",
    url: "https://www.city.joso.lg.jp/kurashi_gyousei/kurashi/iryou_fukushi/disabled_welfare/page003748.html",
    sdgs: "16"
  },
  {
    id: 36,
    facultyName: "早川 和宏",
    department: "法学部 法律学科",
    title: "常総市無料法律相談会",
    role: "助言・指導",
    type: "その他",
    organizer: "東洋大学無料法律相談部",
    eventName: "常総市無料法律相談会",
    date: "2/23",
    location: "常総市 生涯学習センター",
    target: "社会人・一般",
    summary: "常総市無料法律相談会にて本学の無料法律相談部の顧問として、相談対応に当たった。",
    url: "https://sites.google.com/toyo.jp/law/news_f/20250223",
    sdgs: "16"
  },
  {
    id: 37,
    facultyName: "奥乃 真弓",
    department: "法学部 法律学科",
    title: "学会の運営",
    role: "運営参加・支援, その他",
    type: "その他",
    organizer: "国際取引法学会",
    eventName: "国際取引法学会理事副会長、事務局長代行",
    date: "2022/3/27～現在まで",
    location: "―",
    target: "大学生, 大学院生, 教育関係者, 研究者, 社会人・一般, 学術団体, 企業",
    summary: "【国際取引法学会】\n国際取引法学を研究する者（研究者・企業法務・法曹等）のための学会であり、これら3者（研究者・企業法務・法曹等）が協働して国際取引法学の振興を図る「場」と「機会」を提供する。2014年12月に設立総会を開催し、対象とする会員は、大学の研究者、企業の法務部門等の実務家など国籍を問わず国際取引の法律問題にかかわる人すべてである。学会の特徴として、国際取引法学の特性から８つの研究部会（国際契約法制部会、国際通商・投資法制部会、国際知的財産法制部会、国際企業法制部会、国際取引紛争解決法制部会、グローバル・コンプライアンス法制部会、国際金融法制・税制部会、新興国法制部会）を学会の下に設置し、各部会執行部主導の下、定例研究会や共同研究を行う活発な研究を通じて若手研究者の育成を実現することを目的とする。（参照：国際取引法学会「設立趣旨｜学会概要」https://www.asas.or.jp/jaibl/outline/vision.html（2024年3月18日閲覧））\n学会活動としては、各研究部会による部会の報告会に加え、原則として年に2回の全国大会（主に3月と9月）を開催し、研究活動はHPを通じて開示されている。また、学会活動としては、外国判例評釈や研究成果の発表（論文掲載）、学会賞、エッセイコンテストなどの研究成果の報告を行っている。（参照：国際取引法学会「お知らせ」https://www.asas.or.jp/jaibl/info/event1.html#019（2024年3月18日閲覧））\n上記のような活動を行う学会の理事副会長および事務局長代行として学会の運営、管理に携わる。",
    url: "https://www.asas.or.jp/jaibl/index.html",
    sdgs: "4, 5, 8, 9"
  }
];
